In [1]:
import numpy as np
import pandas as pd

In [2]:
smartphones=pd.read_csv("/content/smartphones.csv")

In [3]:
smartphones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   model      1020 non-null   object
 1   price      1020 non-null   object
 2   rating     879 non-null    float64
 3   sim        1020 non-null   object
 4   processor  1020 non-null   object
 5   ram        1020 non-null   object
 6   battery    1020 non-null   object
 7   display    1020 non-null   object
 8   camera     1019 non-null   object
 9   card       1013 non-null   object
 10  os         1003 non-null   object
dtypes: float64(1), object(10)
memory usage: 87.8+ KB

In [4]:
smartphones.duplicated().sum()

np.int64(0)

In [5]:
df=smartphones.copy()

In [6]:
df["price"]=df.price.str.replace("₹","").str.replace(",","").astype("int")

In [7]:
df=df.reset_index()

In [8]:
df["index"]=df["index"]+2

In [9]:
processor_rows = set((642,647,649,659,667,701,750,759,819,859,883,884,919,927,929,932,1002))
ram_rows = set((441,485,534,553,584,610,613,642,647,649,659,667,701,750,759,819,859,884,919,927,929,932,990,1002))
battery_rows = set((113,151,309,365,378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,756,759,764,819,855,859,884,915,916,927,929,932,990,1002))
display_rows = set((378,441,450,553,584,610,613,630,642,647,649,659,667,701,750,759,764,819,859,884,915,916,927,929,932,990,1002))
camera_rows = set((100,113,151,157,161,238,273,308,309,323,324,365,367,378,394,441,450,484,506,534,553,571,572,575,584,610,613,615,630,642,647,649,659,667,684,687,705,711,723,728,750,756,759,764,792,819,846,854,855,858,883,884,896,915,916,927,929,932,945,956,990,995,1002,1016 ))

In [10]:
df[df["index"].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
...,...,...,...,...,...,...,...,...,...,...,...,...
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
988,990,Nokia 5310 Dual Sim,3399,NaN,Dual Sim,"8 MB RAM, 16 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [11]:
df[df["index"].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
640,642,Nokia 105 Plus,1299,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",800 mAh Battery,"1.77 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
647,649,Motorola Moto A10,1339,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1750 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",NaN,NaN
657,659,Zanco Tiny T1,2799,NaN,Single Sim,"32 MB RAM, 32 MB inbuilt",200 mAh Battery,"0.49 inches, 64 x 32 px Display",No Rear Camera,No FM Radio,Bluetooth,NaN
665,667,itel it2163S,958,NaN,Dual Sim,"4 MB RAM, 4 MB inbuilt",1200 mAh Battery,"1.8 inches, 160 x 128 px Display",No Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,NaN
748,750,Nokia 400 4G,3290,NaN,"Dual Sim, 4G, VoLTE, Wi-Fi",2000 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear & 0.3 MP Front Camera,"Memory Card Supported, upto 64 GB",Bluetooth,Browser,NaN
757,759,Karbonn KU3i,995,NaN,Dual Sim,"52 MB RAM, 32 MB inbuilt",1000 mAh Battery,"1.8 inches, 128 x 160 px Display",No Rear Camera,"Memory Card Supported, upto 16 GB",Bluetooth,NaN
817,819,itel Magic X,2239,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",No 3G,T117,"48 MB RAM, 128 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",1.3 MP Rear Camera,"Memory Card Supported, upto 64 GB"
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
927,929,Samsung Guru E1200,1685,NaN,Single Sim,No Wifi,800 mAh Battery,"1.5 inches, 128 x 128 px Display",No Rear Camera,No FM Radio,NaN,NaN
930,932,iKall K88 Pro 4G,2099,NaN,"Dual Sim, 3G, 4G, VoLTE","48 MB RAM, 128 MB inbuilt",1800 mAh Battery,"2.4 inches, 240 x 360 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 128 GB",Bluetooth,Browser
1000,1002,XTouch F40 Flip,1999,NaN,Dual Sim,No 3G,No Wifi,"32 MB RAM, 32 MB inbuilt",800 mAh Battery,"1.77 inches, 240 x 320 px Display",Dual Display,1.3 MP Rear Camera

In [12]:
df[df["index"].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)].price.mean()

np.float64(2537.6923076923076)

In [13]:
df=df[df["price"]>=3400]

In [14]:
df[df["index"].isin(processor_rows | ram_rows | battery_rows | display_rows | camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [15]:
df[df["index"].isin(processor_rows & ram_rows & battery_rows & display_rows & camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [16]:
df[df["index"].isin(processor_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
645,647,Nokia 2760 Flip,5490,NaN,"Dual Sim, 3G, 4G, Wi-Fi",1450 mAh Battery,"3.6 inches, 240 x 320 px Display",5 MP Rear & 5 MP Front Camera,"Memory Card Supported, upto 32 GB",Kaios v3.0,Bluetooth,NaN
857,859,LG Folder 2,11999,NaN,"Single Sim, 3G, 4G, Wi-Fi","1 GB RAM, 8 GB inbuilt",1470 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,Bluetooth,NaN
882,884,Nokia 5710 XpressAudio,4799,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"
925,927,Nokia 3310 4G,3999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","256 MB RAM, 512 MB inbuilt",1200 mAh Battery,"2.4 inches, 240 x 320 px Display",2 MP Rear Camera,"Memory Card Supported, upto 32 GB",Bluetooth,Browser

In [17]:
df.drop([645,857,882,925],inplace=True)

In [18]:
df[df["index"].isin(ram_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
483,485,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
582,584,Nokia 8210 4G,3749,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB"

In [19]:
df.drop([582],inplace=True)

In [20]:
df[df["index"].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
376,378,Nokia 2660 Flip,4649,NaN,"Dual Sim, 3G, 4G",No Wifi,Unisoc T107,"48 MB RAM, 128 MB inbuilt",1450 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,0.3 MP Rear Camera
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15,No FM Radio
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt","6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15,No FM Radio
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
754,756,Apple iPod Touch (7th Gen),18900,NaN,Wi-Fi,32 GB inbuilt,"4 inches, 640 x 1136 px Display",8 MP Rear & 1.2 MP Front Camera,iOS v12,No FM Radio,Bluetooth,Browser
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16,No FM Radio
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0,No FM Radio
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt","6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14,No FM Radio

In [21]:
df.drop([376,754,],inplace=True)

In [22]:
temp_df=df[df["index"].isin(battery_rows)]

In [23]:
temp_df.iloc[:,7:].shift(1,axis=1)

,battery,display,camera,card,os
111,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [24]:
x=temp_df.iloc[:,7:].shift(1,axis=1).values

In [25]:
df.loc[temp_df.index,temp_df.columns[7:]]=x

In [26]:
df[df["index"].isin(battery_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [27]:
df[df["index"].isin(display_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14

In [28]:
df[df["index"].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
155,157,Nokia 2780 Flip,4990,NaN,"Dual Sim, 3G, 4G, Wi-Fi","Snapdragon QM215, Quad Core, 1.3 GHz Processor","4 GB RAM, 512 MB inbuilt",1450 mAh Battery,"2.7 inches, 240 x 320 px Display",Dual Display,5 MP Rear Camera,"Memory Card Supported, upto 32 GB"
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
271,273,Nokia 2720 V Flip,6199,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 205 , Dual Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",1500 mAh Battery,"2.8 inches, 240 x 320 px Display",Dual Display,2 MP Rear Camera,Memory Card Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [29]:
df.drop([155,271,],inplace=True)

In [30]:
df[df["index"].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [31]:
temp_df=df[df["index"].isin(camera_rows)]

In [32]:
temp_df[~temp_df["camera"].str.contains("MP")]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...","Foldable Display, Dual Display",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...","Foldable Display, Dual Display",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",Dual Display,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",Dual Display,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",Dual Display,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",Dual Display,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",Dual Display,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",Foldable Display,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display","Foldable Display, Dual Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",Dual Display,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display","Foldable Display, Dual Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...","Foldable Display, Dual Display",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",Foldable Display,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",Foldable Display,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [33]:
temp_df=temp_df[~temp_df["camera"].str.contains("MP")]

In [34]:
df.loc[temp_df.index,"camera"]=temp_df["card"]

In [35]:
df[df["index"].isin(camera_rows)]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
98,100,Vivo X Fold 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
111,113,Apple iPhone 12,51999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
149,151,Apple iPhone 12 Mini,40999,74.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 64 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported
236,238,Xiaomi Mix Fold 2 5G,106990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1 , Octa Core, 3.2 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"8.02 inches, 1914 x 2160 px, 120 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front...,Android v12
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
307,309,Apple iPhone 12 (128GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
321,323,Samsung Galaxy Z Fold 4,154998,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
363,365,Apple iPhone 12 Mini (128GB),45999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 128 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported
439,441,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
448,450,Apple iPhone 15 Pro,130990,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",Bionic A16,"8 GB RAM, 128 GB inbuilt",None,"6.06 inches, 1170 x 2532 px, 120 Hz Display wi...",50 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v15
482,484,Vivo X Fold Plus,113990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4730 mAh Battery with 80W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display wi...",50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera,Android v12
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported
569,571,Samsung Galaxy Z Fold 3,110999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1768 x 2208 px, 120 Hz Display wit...",12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 ...,Android v11
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid)
628,630,Apple iPhone 12 Pro (512GB),139900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 512 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB"
703,705,Oppo Find N 5G,92249,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,50 MP + 16 MP + 13 MP Triple Rear & 32 MP Fron...,Android v11
709,711,OPPO X 2021,134999,86.0,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 256 GB inbuilt",4000 mAh Battery with 45W Fast Charging,"7.4 inches, 1440 x 3200 px Display",64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,64 MP + 16 MP + 12 MP Triple Rear & 16 MP Fron...,Android v11
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB"
762,764,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16
790,792,Xiaomi Mi Mix Fold,109990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 888 , Octa Core, 2.84 GHz Processor","12 GB RAM, 256 GB inbuilt",5020 mAh Battery with 67W Fast Charging,"8.01 inches, 1860 x 2480 px, 90 Hz Display",108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,108 MP + 13 MP + 8 MP Triple Rear & 20 MP Fron...,Android v10
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB"
853,855,Apple iPhone 12 Pro (256GB),119900,80.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","6 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP + 12 MP Triple Rear & 12 MP Fron...,Memory Card Not Supported,iOS v14.0
856,858,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB"
913,915,Apple iPhone 12 Mini (256GB),55999,75.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"5.4 inches, 1080 x 2340 px Display",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
914,916,Apple iPhone 12 (256GB),67999,76.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Bionic A14, Hexa Core, 3.1 GHz Processor","4 GB RAM, 256 GB inbuilt",None,"6.1 inches, 1170 x 2532 px Display with Large ...",12 MP + 12 MP Dual Rear & 12 MP Front Camera,Memory Card Not Supported,iOS v14
943,945,Samsung Galaxy Z Fold 4 (12GB RAM + 1TB),163980,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 1 TB inbuilt",4400 mAh Battery with 25W Fast Charging,"7.6 inches, 1812 x 2176 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 ...,Android v12
954,956,Vivo X Fold 5G (12GB RAM + 512GB),118990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP Quad Rear & 16 MP Front Camera,50 MP Quad Rear & 16 MP Front Camera,Android v12
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB"
1014,1016,Vivo X Fold 2,119990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 66W Fast Charging,"8.03 inches, 1916 x 2160 px, 120 Hz Display",50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,50 MP + 50 MP + 10 MP Triple Rear & 32 MP Fron...,Android v12

In [36]:
pd.set_option("display.max_rows",None)

In [37]:
df.card.value_counts()

card
Memory Card Supported, upto 1 TB                                       171
Memory Card Not Supported                                              123
Android v12                                                            107
Memory Card Supported, upto 512 GB                                     105
Memory Card (Hybrid), upto 1 TB                                         91
Memory Card Supported                                                   89
Memory Card Supported, upto 256 GB                                      87
Android v13                                                             46
Android v11                                                             41
Memory Card (Hybrid)                                                    30
Memory Card (Hybrid), upto 256 GB                                       13
Memory Card (Hybrid), upto 512 GB                                       11
Android v10                                                             11
Memory Card Supported, upto 128 GB                                       6
Memory Card Supported, upto 2 TB                                         5
Memory Card Supported, upto 32 GB                                        4
Memory Card (Hybrid), upto 64 GB                                         3
Memory Card (Hybrid), upto 128 GB                                        3
50 MP Quad Rear & 16 MP Front Camera                                     2
50 MP + 8 MP Dual Rear & 32 MP Front Camera                              2
Android v9.0 (Pie)                                                       2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       2
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                    2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                             2
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
64 MP + 10 MP + 8 MP Triple Rear & 32 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                    1
Android v12.1                                                            1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                        1
Memory Card Supported, upto 1000 GB                                      1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera       1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                   1
iOS v10                                                                  1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                     1
Android v10.0                                                            1
iOS v13                                                                  1
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                  1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                   1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                    1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                  1
HarmonyOS v2.0                                                           1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
5 MP Rear & 2 MP Front Camera                                            1
Memory Card (Hybrid), upto 2 TB                                          1
HarmonyOS                                                                1
48 MP Quad Rear Camera                                                   1
50 MP + 50 MP + 10 MP Triple Rear & 32 MP Front Camera                   1
Name: count, dtype: int64

In [38]:
temp_df=df[df["card"].str.contains("MP")]

In [39]:
df.loc[temp_df.index,"card"]="Memory Card Not Supported"

In [40]:
df.card.value_counts()

card
Memory Card Supported, upto 1 TB       171
Memory Card Not Supported              149
Android v12                            107
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Android v13                             46
Android v11                             41
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Android v10                             11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Android v9.0 (Pie)                       2
Android v12.1                            1
Memory Card Supported, upto 1000 GB      1
iOS v10                                  1
Android v10.0                            1
iOS v13                                  1
HarmonyOS v2.0                           1
Memory Card (Hybrid), upto 2 TB          1
HarmonyOS                                1
Name: count, dtype: int64

In [41]:
df[~df["card"].str.contains("Memory Card")]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
8,10,Nothing Phone 1,26749,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
9,11,OnePlus Nord 2T 5G,28999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
12,14,Xiaomi Redmi Note 12 Pro 5G,24762,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
17,19,OPPO Reno 9 Pro Plus,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","16 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
18,20,OnePlus 10R 5G,32999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
20,22,OnePlus 11R,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front...,Android v13,Bluetooth
21,23,Vivo V25 Pro 5G,35999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
24,26,Vivo V26 Pro,42990,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4800 mAh Battery with 100W Fast Charging,"6.7 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v13,No FM Radio
29,31,OnePlus 11 Pro,69999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 100W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
37,39,Samsung Galaxy S22 Ultra 5G,91999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.8 inches, 1440 x 3080 px, 120 Hz Display wit...",108 MP Quad Rear & 40 MP Front Camera,Android v12,Bluetooth
39,41,OPPO Reno 9 5G,28499,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G, Octa Core, 2.4 GHz Processor","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",64 MP + 2 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
51,53,iQOO Neo 7 5G,29999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
58,60,Samsung Galaxy S23 Plus,84990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
60,62,Xiaomi Redmi Note 13 Pro 5G,17990,78.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Dimensity 720, Octa Core, 2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2460 px, 120 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,Bluetooth
61,63,Vivo S16,29990,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
65,67,Vivo S16 Pro,35499,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 256 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front ...,Android v13,No FM Radio
66,68,OnePlus 10 Pro 5G,60999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
73,75,OnePlus 10T,44999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 150W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
85,87,Motorola Edge 30 5G,22999,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","6 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
91,93,OnePlus Ace Racing Edition 5G,22990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
93,95,Vivo X90 Pro Plus 5G,73999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.78 inches, 1440 x 3200 px, 120 Hz Display wi...",50.3 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
97,99,iQOO 11 5G,59999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 13 MP + 8 MP Triple Rear & 16 MP Front...,Android v13,No FM Radio
102,104,Motorola Moto S30 Pro,23990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888+, Octa Core, 2.9 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 68W Fast Charging,"6.55 inches, 1080 x 2460 px, 144 Hz Display wi...",50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
106,108,Vivo V27 Pro,43999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.73 inches, 1080 x 2400 px, 144 Hz Display wi...",108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front...,Android v13,No FM Radio
107,109,Samsung Galaxy S22 5G,49999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
109,111,OnePlus 10R 5G (12GB RAM + 256GB),36999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
110,112,Tecno Phantom X2,39999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",64 MP + 13 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
112,114,Xiaomi Redmi K50i 5G,22999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 8100, Octa Core, 2.85 GHz Processor","6 GB RAM, 128 GB inbuilt",5080 mAh Battery with 67W Fast Charging,"6.6 inches, 1080 x 2460 px, 144 Hz Display wit...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,Bluetooth
115,117,OPPO Reno8 5G,29340,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
119,121,Samsung Galaxy S23,70990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3900 mAh Battery with 25W Fast Charging,"6.1 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 12 MP Fron...,Android v13,No FM Radio
120,122,Motorola Edge 30 Pro 5G,34999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4800 mAh Battery with 68W Fast Charging,"6.7 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 60 MP Front...,Android v12,No FM Radio
121,123,OnePlus Nord 2T (12GB RAM + 256GB),33900,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
133,135,Nothing Phone 1 (8GB RAM + 256GB),28249,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","8 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
139,141,iQOO Neo 6 5G,28999,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
141,143,OPPO Reno 9 Pro 5G,39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100 Max, Octa Core, 2.85 GHz Processor","16 GB RAM, 256 GB inbuilt",4500 mAh Battery with 67W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Android v13,No FM Radio
146,148,iQOO 7,24990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 870, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4400 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v11,No FM Radio
163,165,Oppo Reno 10 Pro Plus,58990,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4700 mAh Battery with 80W Fast Charging,"6.73 inches, 1080 x 2412 px, 120 Hz Display wi...",64 MP Quad Rear & 32 MP Front Camera,Android v13,No FM Radio
168,170,iQOO 9 SE 5G,30990,83.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888 , Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 66W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front...,Android v12,No FM Radio
170,172,Letv Y1 Pro,5499,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T310, Quad Core, 2 GHz Processor","4 GB RAM, 32 GB inbuilt",4000 mAh Battery,"6.54 inches, 720 x 1560 px Display with Small ...",8 MP + Depth Sensor Dual Rear & 5 MP Front Camera,Android v11,No FM Radio
183,185,Motorola Moto X40,39999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4600 mAh Battery with 125W Fast Charging,"6.7 inches, 1080 x 2400 px, 165 Hz Display",50 MP + 50 MP + 12 MP Triple Rear & 60 MP Fron...,Android v13,No FM Radio
186,188,OnePlus Nord 3 5G,27999,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8200, Octa Core, 3.1 GHz Processor","8 GB RAM, 128 GB inbuilt",4200 mAh Battery with 120W Fast Charging,"6.43 inches, 1080 x 2400 px, 90 Hz Display wit...",50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front...,Android v11,No FM Radio
189,191,LeEco S1 Pro,10999,65.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Tiger T7150, Quad Core, 1.8 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with 10W Fast Charging,"6.5 inches, 720 x 1600 px Display with Small N...",13 MP + Depth Sensor Dual Rear & 5 MP Front Ca...,Android v11,No FM Radio
196,198,OPPO Reno 8 Pro House of Dragon Edition,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
202,204,Motorola Edge 30 Ultra,54999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",4610 mAh Battery with 125W Fast Charging,"6.67 inches, 1080 x 2400 px, 144 Hz Display wi...",200 MP + 50 MP + 12 MP Triple Rear & 60 MP Fro...,Android v12,No FM Radio
203,205,Xiaomi 13 Ultra 5G,71999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 120W Fast Charging,"6.6 inches, 1440 x 3200 px, 120 Hz Display wit...",108 MP Quad Rear & 32 MP Front Camera,Android v12,No FM Radio
206,208,Nothing Phone 1 (12GB RAM + 256GB),35999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G Plus, Octa Core, 2.5 GHz Proce...","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 33W Fast Charging,"6.55 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 50 MP Dual Rear & 16 MP Front Camera,Android v12,No FM Radio
209,211,Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB),27994,82.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster","Dimensity 1080, Octa Core, 2.6 GHz Processor","8 GB RAM, 256 GB inbuilt",5000 mAh Battery with 67W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
211,213,Vivo V25 Pro (12GB RAM + 256GB),39999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Dimensity 1300, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",4830 mAh Battery with 66W Fast Charging,"6.56 inches, 1080 x 2376 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
215,217,Honor X9a,27999,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 695, Octa Core, 2.2 GHz Processor","8 GB RAM, 256 GB inbuilt",5100 mAh Battery with 40W Fast Charging,"6.67 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 5 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
216,218,Google Pixel 7 Pro 5G,81999,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","12 GB RAM, 128 GB inbuilt",5000 mAh Battery with 30W Fast Charging,"6.7 inches, 1440 x 3120 px, 120 Hz Display wit...",50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Fr...,Android v13,No FM Radio
220,222,Xiaomi Redmi K60,29990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",5500 mAh Battery with 67W Fast Charging,"6.67 inches, 1440 x 3200 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
223,225,Motorola Edge 30 5G (8GB RAM + 128GB),24999,85.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 778G+, Octa Core, 2.5 GHz Processor","8 GB RAM, 128 GB inbuilt",4020 mAh Battery with 33W Fast Charging,"6.5 inches, 1080 x 2400 px, 144 Hz Display wit...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
228,230,Realme GT Neo 3T,24999,79.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 870, Octa Core, 3.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.62 inches, 1080 x 2400 px, 120 Hz Display wi...",64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v12,No FM Radio
229,231,OPPO Reno 8 Pro 5G,45999,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 8100-Max, Octa Core, 2.85 GHz Processor","12 GB RAM, 256 GB inbuilt",4500 mAh Battery with 80W Fast Charging,"6.7 inches, 1080 x 2412 px, 120 Hz Display wit...",50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front ...,Android v12,No FM Radio
230,232,OnePlus 10 Pro 5G (12GB RAM + 256GB),65499,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 80W Fast Charging,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front...,Android v12,No FM Radio
231,233,iQOO 11 Pro 5G,58990,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4700 mAh Battery with 200W Fast Charging,"6.78 inches, 1440 x 3200 px, 144 Hz Display wi...",50 MP + 50 MP + 13 MP Triple Rear & 16 MP Fron...,Android v13,No FM Radio
244,246,Google Pixel 7 5G,53100,86.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Google Tensor G2, Octa Core, 2.85 GHz Processor","8 GB RAM, 128 GB inbuilt",4355 mAh Battery with 30W Fast Charging,"6.3 inches, 1080 x 2400 px, 90 Hz Display with...",50 MP + 12 MP Dual Rear & 10.8 MP Front Camera,Android v13,No FM Radio
249,251,Nubia Red Magic 8 Pro 5G,46990,84.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",6000 mAh Battery with 80W Fast Charging,"6.8 inches, 1116 x 2480 px, 120 Hz Display",50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front ...,Android v13,No FM Radio
251,253,Tecno Phantom X2 Pro,49999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","12 GB RAM, 256 GB inbuilt",5160 mAh Battery with 45W Fast Charging,"6.8 inches, 1080 x 2400 px, 120 Hz Display wit...",50 MP + 50 MP + 13 MP Triple Rear & 32 MP Fron...,Android v12,Bluetooth
257,259,Samsung Galaxy S22 Plus 5G,64449,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8 Gen1, Octa Core, 3 GHz Processor","8 GB RAM, 128 GB inbuilt",4500 mAh Battery with 45W Fast Charging,"6.6 inches, 1080 x 2340 px, 120 Hz Display wit...",50 MP + 12 MP + 10 MP Triple Rear & 10 MP Fron...,Android v12,Bluetooth
258,260,Vivo U3x,8990,71.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 480 , Octa Core, 2 GHz Processor","6 GB RAM, 64 GB inbuilt",5000 mAh Battery with 18W Fast Charging,"6.58 inches, 1080 x 2408 px, 90 Hz Display wit...",13 MP + 2 MP Dual Rear & 8 MP Front Camera,Android v11,No FM Radio

In [42]:
temp_df=df[~df["card"].str.contains("Memory Card")]

In [43]:
df.loc[temp_df.index,"os"]=temp_df["card"]

In [44]:
df.loc[temp_df.index,"card"]="Memory Card Not Supported"

In [45]:
df.card.value_counts()

card
Memory Card Not Supported              362
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      87
Memory Card (Hybrid)                    30
Memory Card (Hybrid), upto 256 GB       13
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       6
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card Supported, upto 1000 GB      1
Memory Card (Hybrid), upto 2 TB          1
Name: count, dtype: int64

In [46]:
df["os"].value_counts()

os
Android v12                           394
Android v11                           274
Android v13                            91
Android v10                            69
Android v9.0 (Pie)                     29
Android v10.0                          23
iOS v16                                15
iOS v15                                12
Android v8.1 (Oreo)                    10
iOS v14                                 6
Memory Card Not Supported               6
Android v8.0 (Oreo)                     4
Android v11.0                           4
iOS v13                                 4
iOS v15.0                               3
Memory Card (Hybrid), upto 2 TB         2
Memory Card Supported, upto 256 GB      2
Android v5.1.1 (Lollipop)               2
Android v12.1                           2
HarmonyOS v2.0                          2
iOS v14.0                               2
EMUI v12                                2
Android v6.0 (Marshmallow)              2
Memory Card (Hybrid), upto 256 GB       2
Harmony v2.0                            2
HarmonyOS v2                            1
iOS v13.0                               1
Hongmeng OS v3.0                        1
Bluetooth                               1
Android v4.4.2 (KitKat)                 1
Android v5.1 (Lollipop)                 1
iOS v17                                 1
iOS v12.3                               1
RTOS (Series 30+)                       1
Pragati OS (Powered by Android)         1
Hongmeng OS v4.0                        1
iOS v10                                 1
Memory Card (Hybrid)                    1
Memory Card Supported, upto 128 GB      1
HarmonyOS                               1
Android v7.1 (Nougat)                   1
Android                                 1
Android v9 (Pie)                        1
Name: count, dtype: int64

In [47]:
df[df["os"].str.contains("Memory Card")]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card Not Supported,Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,Memory Card Not Supported,"Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,"Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,Memory Card Not Supported,"Memory Card (Hybrid), upto 256 GB"

In [48]:
temp_df=df[df["os"].str.contains("Memory Card")]

In [49]:
temp_df1=temp_df[~temp_df["os"].str.contains("Memory Card Not Supported")]

In [50]:
df.loc[temp_df1.index,"card"]=temp_df1["os"]

In [51]:
df[df["os"].str.contains("Memory Card")]

,index,model,price,rating,sim,processor,ram,battery,display,camera,card,os
159,161,Oppo Find N2 5G,94990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",4520 mAh Battery with 67W Fast Charging,"7.1 inches, 1792 x 1920 px, 120 Hz Display wit...",50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32...,Memory Card Not Supported,Memory Card Not Supported
306,308,Samsung Galaxy Z Flip 3,69999,84.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3300 mAh Battery with 15W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
322,324,Royole FlexPai 2,109999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",4450 mAh Battery,"7.8 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
365,367,OPPO Find N Flip,89990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000, Octa Core, 3.05 GHz Processor","8 GB RAM, 128 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1200 x 2400 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
392,394,OPPO Find N2 Flip,70990,88.0,"Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","8 GB RAM, 256 GB inbuilt",4300 mAh Battery with 44W Fast Charging,"6.8 inches, 1080 x 2520 px, 120 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
504,506,Samsung Galaxy Z Flip 4 5G,89999,88.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor","8 GB RAM, 128 GB inbuilt",3700 mAh Battery with 25W Fast Charging,"6.7 inches, 1080 x 2640 px, 120 Hz Display wit...",12 MP + 12 MP Dual Rear & 10 MP Front Camera,Memory Card Not Supported,Memory Card Not Supported
570,572,LG Wing 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 765G , Octa Core, 2.4 GHz Processor","8 GB RAM, 128 GB inbuilt",4000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display",64 MP + 13 MP + 12 MP Triple Rear & 32 MP Fron...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
613,615,Oukitel WP21,22990,82.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi","Helio G99, Octa Core, 2.2 GHz Processor","12 GB RAM, 256 GB inbuilt",9800 mAh Battery with 66W Fast Charging,"6.78 inches, 1080 x 2400 px, 120 Hz Display",64 MP + 20 MP + 2 MP Triple Rear & Main Front ...,Memory Card (Hybrid),Memory Card (Hybrid)
682,684,LG V60 ThinQ,79990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Snapdragon 865, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",5000 mAh Battery with Fast Charging,"6.8 inches, 1080 x 2460 px Display with Punch ...",64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Fro...,"Memory Card (Hybrid), upto 2 TB","Memory Card (Hybrid), upto 2 TB"
721,723,Asus ROG Phone 6D Ultimate,107990,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC","Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor","16 GB RAM, 512 GB inbuilt",6000 mAh Battery with 65W Fast Charging,"6.78 inches, 1080 x 2448 px, 165 Hz Display",50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front...,Memory Card Not Supported,Memory Card Not Supported
726,728,Huawei Mate Xs 2,162990,89.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 512 GB inbuilt",4600 mAh Battery with 66W Fast Charging,"7.8 inches, 2200 x 2480 px, 120 Hz Display wit...",50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Fro...,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"
844,846,CAT S22 Flip,14999,NaN,"Single Sim, 3G, 4G, VoLTE, Wi-Fi","Qualcomm 215, Quad Core, 1.3 GHz Processor","2 GB RAM, 16 GB inbuilt",2000 mAh Battery,"4 inches, 480 x 640 px Display",5 MP Rear & 2 MP Front Camera,"Memory Card Supported, upto 128 GB","Memory Card Supported, upto 128 GB"
894,896,Royole FlexPai 3 5G,149999,87.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi","Snapdragon 888, Octa Core, 2.84 GHz Processor","8 GB RAM, 128 GB inbuilt",3360 mAh Battery,"7.2 inches, 1440 x 1920 px Display",64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front...,"Memory Card Supported, upto 256 GB","Memory Card Supported, upto 256 GB"
993,995,Huawei Mate X,169000,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Bl...","Kirin 990, Octa Core, 2.86 GHz Processor","8 GB RAM, 512 GB inbuilt",4500 mAh Battery with 55W Fast Charging,"8 inches, 2200 x 2480 px Display",48 MP Quad Rear Camera,"Memory Card (Hybrid), upto 256 GB","Memory Card (Hybrid), upto 256 GB"

In [52]:
temp_df=df[df["os"].str.contains("Memory Card")]

In [53]:
df.loc[temp_df.index,"os"]=np.nan

In [54]:
df["os"].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
iOS v13                              4
Android v11.0                        4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
Android v12.1                        2
EMUI v12                             2
Android v5.1.1 (Lollipop)            2
HarmonyOS v2.0                       2
iOS v14.0                            2
Harmony v2.0                         2
Android v6.0 (Marshmallow)           2
Android v5.1 (Lollipop)              1
Android v4.4.2 (KitKat)              1
iOS v17                              1
iOS v12.3                            1
HarmonyOS v2                         1
iOS v13.0                            1
Pragati OS (Powered by Android)      1
Hongmeng OS v3.0                     1
iOS v10                              1
RTOS (Series 30+)                    1
Bluetooth                            1
Hongmeng OS v4.0                     1
HarmonyOS                            1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [55]:
temp_df=df[df["os"]=="Bluetooth"]

In [56]:
df.loc[temp_df.index,"os"]=np.nan

In [57]:
df["os"].value_counts()

os
Android v12                        394
Android v11                        274
Android v13                         91
Android v10                         69
Android v9.0 (Pie)                  29
Android v10.0                       23
iOS v16                             15
iOS v15                             12
Android v8.1 (Oreo)                 10
iOS v14                              6
Android v11.0                        4
iOS v13                              4
Android v8.0 (Oreo)                  4
iOS v15.0                            3
EMUI v12                             2
Android v12.1                        2
Harmony v2.0                         2
iOS v14.0                            2
Android v5.1.1 (Lollipop)            2
Android v6.0 (Marshmallow)           2
HarmonyOS v2.0                       2
Android v4.4.2 (KitKat)              1
Android v5.1 (Lollipop)              1
iOS v12.3                            1
iOS v13.0                            1
HarmonyOS v2                         1
iOS v17                              1
Pragati OS (Powered by Android)      1
iOS v10                              1
RTOS (Series 30+)                    1
Hongmeng OS v3.0                     1
Hongmeng OS v4.0                     1
HarmonyOS                            1
Android v7.1 (Nougat)                1
Android                              1
Android v9 (Pie)                     1
Name: count, dtype: int64

In [58]:
df["sim"].value_counts()

sim
Dual Sim, 3G, 4G, VoLTE, Wi-Fi                               317
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      268
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           155
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, IR Blaster                54
Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC, IR Blaster           52
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, IR Blaster                    46
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                           46
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC                  7
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC                      7
Dual Sim, 3G, 4G, Wi-Fi                                        7
Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster                5
Single Sim, 3G, 4G, VoLTE, Wi-Fi, NFC                          4
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi                       3
Single Sim, 3G, 4G, VoLTE, Wi-Fi                               3
Dual Sim, 3G, 4G, Wi-Fi, NFC                                   2
Single Sim, 3G, 4G, Wi-Fi, NFC                                 1
Single Sim, 3G, 4G, 5G, VoLTE, Wi-Fi                           1
Dual Sim, 3G, 4G, VoLTE                                        1
Dual Sim, 3G, Wi-Fi                                            1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster           1
Dual Sim, 3G, 4G, 5G, VoLTE, Vo5G, Wi-Fi, NFC, IR Blaster      1
Name: count, dtype: int64

In [59]:
df["processor"].value_counts()

processor
Dimensity 700 5G, Octa Core, 2.2 GHz Processor         29
Helio P35, Octa Core, 2.3 GHz Processor                27
Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor       26
Snapdragon 695, Octa Core, 2.2 GHz Processor           23
Snapdragon 680, Octa Core, 2.4 GHz Processor           23
Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor        23
Helio G35, Octa Core, 2.3 GHz Processor                20
Snapdragon  680, Octa Core, 2.4 GHz Processor          18
Snapdragon  8 Gen1, Octa Core, 3 GHz Processor         18
Snapdragon 8 Gen1, Octa Core, 3 GHz Processor          17
Bionic A15, Hexa Core, 3.22 GHz Processor              16
Snapdragon  695, Octa Core, 2.2 GHz Processor          16
Dimensity  810 5G, Octa Core, 2.4 GHz Processor        15
Snapdragon 870, Octa Core, 3.2 GHz Processor           15
Helio G99, Octa Core, 2.2 GHz Processor                14
Helio G80, Octa Core, 2 GHz Processor                  14
Snapdragon 778G, Octa Core, 2.4 GHz Processor          12
Dimensity 1080, Octa Core, 2.6 GHz Processor           12
Dimensity 810 5G, Octa Core, 2.4 GHz Processor         12
Snapdragon  8+ Gen1, Octa Core, 3.2 GHz Processor      12
Helio G96, Octa Core, 2.05 GHz Processor               12
Dimensity  920 5G, Octa Core, 2.5 GHz Processor        11
Snapdragon 888, Octa Core, 2.84 GHz Processor          11
Snapdragon  888 , Octa Core, 2.84 GHz Processor        10
Helio G25, Octa Core, 2 GHz Processor                  10
Helio A22, Quad Core, 2 GHz Processor                  10
Helio  G85, Octa Core, 2 GHz Processor                 10
Tiger T612, Octa Core, 1.82 GHz Processor               9
Helio G37, Octa Core, 2.3 GHz Processor                 9
Octa Core Processor                                     9
Snapdragon 720G, Octa Core, 2.3 GHz Processor           8
Helio G88, Octa Core, 2 GHz Processor                   8
Dimensity 1300, Octa Core, 3 GHz Processor              8
Bionic A14, Hexa Core, 3.1 GHz Processor                8
Snapdragon  870, Octa Core, 3.2 GHz Processor           7
Bionic  A16, Hexa Core Processor                        7
Snapdragon 865, Octa Core, 2.84 GHz Processor           7
Helio G95, Octa Core, 2.05 GHz Processor                7
Dimensity 9000 Plus, Octa Core, 3.2 GHz Processor       6
Exynos 850, Octa Core, 2 GHz Processor                  6
Helio G85, Octa Core, 2 GHz Processor                   6
Helio P22, Octa Core, 2 GHz Processor                   6
Helio  G96, Octa Core, 2.05 GHz Processor               6
Dimensity 8100 Max, Octa Core, 2.85 GHz Processor       6
Dimensity  8100, Octa Core, 2.85 GHz Processor          5
Dimensity 8200, Octa Core, 3.1 GHz Processor            5
Exynos  2100, Octa Core, 2.9 GHz Processor              5
Snapdragon  7 Gen1, Octa Core, 2.36 GHz Processor       5
Snapdragon 778G Plus, Octa Core, 2.5 GHz Processor      5
Dimensity 1200, Octa Core, 3 GHz Processor              5
Snapdragon  732G, Octa Core, 2.3 GHz Processor          5
Snapdragon  778G, Octa Core, 2.4 GHz Processor          5
A13 Bionic, Hexa Core, 2.65 GHz Processor               5
Unisoc  SC9863A, Octa Core, 1.6 GHz Processor           5
Snapdragon  695 , Octa Core, 2.2 GHz Processor          5
Snapdragon 695 , Octa Core, 2.2 GHz Processor           5
Dimensity 720, Octa Core, 2 GHz Processor               4
Dimensity 800U, Octa Core, 2.4 GHz Processor            4
Snapdragon 4 Gen 1, Octa Core, 2 GHz Processor          4
Exynos  1280, Octa Core, 2.4 GHz Processor              4
Snapdragon  480 , Octa Core, 2 GHz Processor            4
Snapdragon  778G , Octa Core, 2.4 GHz Processor         4
Dimensity 900, Octa Core, 2 GHz Processor               4
Exynos 990, Octa Core, 2.73 GHz Processor               4
Dimensity 9000, Octa Core, 3.05 GHz Processor           4
Unisoc  T606, Octa Core, 1.6 GHz Processor              4
Exynos  990, Octa Core, 2.73 GHz Processor              3
Snapdragon  665, Octa Core, 2 GHz Processor             3
 Snapdragon  695, Octa Core, 2.2 GHz Processor          3
Snapdragon  8 Gen2, Octa Core, 3.2 GHz Processor        3
Dimensity  930, Octa Core, 2.2 GHz Processor            3
Snapdragon 845, Octa Core, 2.8 GHz Processor            3
Snapdragon 480+, Octa Core, 2.2 GHz Processor           3
Snapdragon  865 , Octa Core, 2.84 GHz Processor         3
Helio  G99, Octa Core, 2.2 GHz Processor                3
Snapdragon 888+, Octa Core, 2.9 GHz Processor           3
Exynos 1280, Octa Core, 2.4 GHz Processor               3
Snapdragon 765G , Octa Core, 2.4 GHz Processor          3
Snapdragon  888+, Octa Core, 2.9 GHz Processor          3
Tiger  T616, Octa Core, 1.8 GHz Processor               3
Bionic  A16                                             3
Qualcomm 215, Quad Core, 1.3 GHz Processor              3
Dimensity 700, Octa Core, 2.2 GHz Processor             3
Helio  G25, Octa Core, 2 GHz Processor                  3
Helio G95, Octa Core, 2 GHz Processor                   3
Dimensity 8100-Max, Octa Core, 2.85 GHz Processor       3
Quad Core, 1.3 GHz Processor                            3
Dimensity 810, Octa Core, 2.4 GHz Processor             3
Helio G96, Octa Core, 2 GHz Processor                   3
Dimensity  700 5G, Octa Core, 2.2 GHz Processor         3
Octa Core, 2 GHz Processor                              3
Exynos  850, Octa Core, 2 GHz Processor                 3
Snapdragon 765G, Octa Core, 2.4 GHz Processor           3
Dimensity  1300, Octa Core, 3 GHz Processor             3
Exynos 1330, Octa Core, 2.4 GHz Processor               3
Snapdragon  750G, Octa Core, 2.2 GHz Processor          2
Helio G70, Octa Core, 2 GHz Processor                   2
Kirin  990, Octa Core, 2.86 GHz Processor               2
Helio, Octa Core Processor                              2
SC9863A, Octa Core, 1.6 GHz Processor                   2
Snapdragon  480+, Octa Core, 2.2 GHz Processor          2
Dimensity  8200, Octa Core, 3.1 GHz Processor           2
Quad Core, 1.6 GHz Processor                            2
Unisoc SC9863A, Octa Core, 1.6 GHz Processor            2
Dimensity 9200, Octa Core, 3.05 GHz Processor           2
Snapdragon 732G , Octa Core, 2.3 GHz Processor          2
Google  Tensor, Octa Core Processor                     2
Google  Tensor, Octa Core, 2.8 GHz Processor            2
Dimensity 920 5G, Octa Core, 2.5 GHz Processor          2
Snapdragon 712, Octa Core, 2.3 GHz Processor            2
Snapdragon 778G+, Octa Core Processor                   2
Dimensity  900, Octa Core, 2 GHz Processor              2
Exynos 9611, Octa Core, 2.3 GHz Processor               2
Helio P95, Octa Core, 2.2 GHz Processor                 2
Snapdragon  439 , Octa Core, 2 GHz Processor            2
Snapdragon  888, Octa Core, 2.84 GHz Processor          2
Snapdragon  750G , Octa Core, 2.2 GHz Processor         2
Dimensity  900 5G, Octa Core, 2.4 GHz Processor         2
Exynos 9825, Octa Core, 2.73 GHz Processor              2
Snapdragon 7 Gen1, Octa Core, 2.36 GHz Processor        2
Helio G37, Octa Core, 1.8 GHz Processor                 2
Dimensity 8100, Octa Core, 2.85 GHz Processor           2
Tiger T616, Octa Core, 2 GHz Processor                  2
Unisoc  T610, Octa Core, 1.8 GHz Processor              2
Dimensity 700, Octa Core, 2 GHz Processor               2
Snapdragon 690, Octa Core, 2 GHz Processor              2
Unisoc  SC9863a, Octa Core, 1.6 GHz Processor           2
Snapdragon  765G , Octa Core, 2.4 GHz Processor         2
Snapdragon  4 Gen 1, Octa Core, 2 GHz Processor         2
Unisoc T612, Octa Core, 1.8 GHz Processor               2
Helio P35 , Octa Core, 2.3 GHz Processor                2
Snapdragon 865 , Octa Core, 2.84 GHz Processor          2
Snapdragon  778G Plus, Octa Core, 2.5 GHz Processor     2
Snapdragon  720G, Octa Core, 2.3 GHz Processor          2
Snapdragon 678, Octa Core, 2.2 GHz Processor            2
Dimensity  9000, Octa Core, 3.05 GHz Processor          2
Helio G85 , Octa Core, 2 GHz Processor                  2
Snapdragon 855+, Octa Core, 2.96 GHz Processor          2
Bionic  A15, Hexa Core, 3.22 GHz Processor              2
Dimensity 700 , Octa Core, 2.2 GHz Processor            2
Tiger  T310, Quad Core, 2 GHz Processor                 2
Snapdragon 6 Gen 1, Octa Core, 2.2 GHz Processor        2
Snapdragon 778G+, Octa Core, 2.5 GHz Processor          2
Dimensity 800U , Octa Core, 2.4 GHz Processor           2
Snapdragon 662 , Octa Core, 2 GHz Processor             2
Unisoc  T606, Octa Core, 2 GHz Processor                2
Exynos 9820, Octa Core, 2.7 GHz Processor               2
Helio P60, Octa Core, 2 GHz Processor                   2
Snapdragon 439, Octa Core, 2 GHz Processor              2
Snapdragon 460, Octa Core, 1.8 GHz Processor            2
Snapdragon  675, Octa Core, 2 GHz Processor             2
Exynos 1200, Octa Core, 2.4 GHz Processor               1
 Snapdragon 695, Octa Core, 2.2 GHz Processor           1
Quad Core, 1.4 GHz Processor                            1
Snapdragon 460 , Octa Core, 1.8 GHz Processor           1
Bionic A16                                              1
Dimensity  900, Octa Core, 2.4 GHz Processor            1
Dimensity 900, Octa Core, 2.4 GHz Processor             1
Exynos  2300, Octa Core Processor                       1
Tiger T310, Quad Core, 2 GHz Processor                  1
Tiger T7150, Quad Core, 1.8 GHz Processor               1
Helio  P22 , Octa Core, 2 GHz Processor                 1
Exynos 1380, Octa Core Processor                        1
Google Tensor G2, Octa Core, 2.85 GHz Processor         1
Dimensity 930, Octa Core, 2.2 GHz Processor             1
Apple  A13                                              1
Dimensity  1200 Max, Octa Core, 3 GHz Processor         1
Bionic A16, Hexa Core Processor                         1
Snapdragon 870 , Octa Core, 3.2 GHz Processor           1
Helio P23, Octa Core, 2.5 GHz Processor                 1
Snapdragon MSM8939, Octa Core, 1.5 GHz Processor        1
Unisoc  A55, Octa Core, 1.6 GHz Processor               1
Snapdragon 7 Gen1, Octa Core, 2.4 GHz Processor         1
Octa Core, 1.8 GHz Processor                            1
Snapdragon 450, Octa Core, 1.8 GHz Processor            1
Snapdragon 710, Octa Core, 2.2 GHz Processor            1
Exynos 7885, Octa Core, 2.2 GHz Processor               1
Google  Tensor G2, Octa Core, 2.85 GHz Processor        1
Snapdragon  8+ Gen1 , Octa Core, 3.2 GHz Processor      1
Helio P70, Octa Core, 2.1 GHz Processor                 1
Helio  G90T, Octa Core, 2.05 GHz Processor              1
Helio P35, Octa Core, 1.8 GHz Processor                 1
Snapdragon  855, Octa Core, 2.8 GHz Processor           1
Tiger T700, Octa Core, 1.8 GHz Processor                1
Google Tensor, Octa Core, 2.8 GHz Processor             1
Unisoc  SC9836A, Quad Core, 1.6 GHz Processor           1
Helio  G37, Octa Core, 2.3 GHz Processor                1
Snapdragon 615, Octa Core, 1.5 GHz Processor            1
Helio MT6580, Quad Core, 1.3 GHz Processor              1
Helio  G95, Octa Core, 2.05 GHz Processor               1
Tiger T610, Octa Core, 1.82 GHz Processor               1
Snapdragon 8+ Gen 2, Octa Core Processor                1
Snapdragon 835, Octa Core, 2.35 GHz Processor           1
Unisoc  SC9832E, Quad Core, 1.4 GHz Processor           1
Sanpdragon 680, Octa Core, 2.4 GHz Processor            1
Snapdragon  720G , Octa Core, 2.3 GHz Processor         1
Snapdragon 888+ , Octa Core, 2.9 GHz Processor          1
Snapdragon  680 , Octa Core, 2.4 GHz Processor          1
Tiger T606, Octa Core, 2 GHz Processor                  1
Unisoc T606, Octa Core, 1.6 GHz Processor               1
Helio  P35, Octa Core, 2.3 GHz Processor                1
Snapdragon 801, Octa Core, 1.5 GHz Processor            1
Snapdragon 860, Octa Core, 2.96 GHz Processor           1
Snapdragon 775                                          1
Unisoc, Octa Core Processor                             1
Snapdragon 855, Octa Core, 2.8 GHz Processor            1
Snapdragon 730, Octa Core, 2.2 GHz Processor            1
Snapdragon  810, Octa Core, 2.4 GHz Processor           1
Bionic  A17, Octa Core Processor                        1
Exynos 1280, Octa Core Processor                        1
Spreadtrum  SC7731E, Quad Core, 1.3 GHz Processor       1
Tiger  T610, Octa Core, 1.8 GHz Processor               1
Snapdragon  6 Gen 1, Octa Core, 2.2 GHz Processor       1
Tiger T610, Quad Core, 1.8 GHz Processor                1
Dimensity  9200, Octa Core Processor                    1
Kirin  9000, Octa Core, 3.13 GHz Processor              1
Unisoc T610, Octa Core, 1.8 GHz Processor               1
Unisoc T117                                             1
Snapdragon 732G, Octa Core, 2.3 GHz Processor           1
Snapdragon 720G , Octa Core, 2.3 GHz Processor          1
Snapdragon 425, Quad Core, 1.4 GHz Processor            1
Fusion APL1024, Quad Core, 2.37 GHz Processor           1
Snapdragon  210, Quad Core, 1.1 GHz Processor           1
Snapdragon  765G, Octa Core, 2.4 GHz Processor          1
Exynos 9825, Octa Core, 2.7 GHz Processor               1
Exynos 7904, Octa Core, 1.8 GHz Processor               1
Snapdragon  865, Octa Core, 2.84 GHz Processor          1
Exynos  9611 , Octa Core, 2.3 GHz Processor             1
Helio P60, Octa Core, 1.99 GHz Processor                1
Snapdragon  782G, Octa Core, 2.7 GHz Processor          1
Dimensity 8100 Ultra, Octa Core, 2.85 GHz Processor     1
Spreadtrum  SC7731, Quad Core, 1.3 GHz Processor        1
Snapdragon 662, Octa Core, 2 GHz Processor              1
Kirin 9000E, Octa Core, 3.13 GHz Processor              1
Helio A25, Octa Core, 1.8 GHz Processor                 1
Snapdragon  712 , Octa Core, 2.3 GHz Processor          1
Unisoc SC7731E, Quad Core, 1.3 GHz Processor            1
Helio  P22, Octa Core, 2 GHz Processor                  1
Snapdragon  730G, Octa Core, 2.2 GHz Processor          1
Dimensity 9200, Octa Core Processor                     1
Snapdragon 730G, Octa Core, 2.2 GHz Processor           1
Exynos 9810, Octa Core, 2.7 GHz Processor               1
Dimensity 1100 5G, Octa Core, 2.6 GHz Processor         1
Octa Core, 2.2 GHz Processor                            1
Google Tensor 3, Octa Core Processor                    1
Snapdragon 8 Gen1 , Octa Core, 3 GHz Processor          1
Tiger T610, Octa Core, 1.8 GHz Processor                1
Kirin 990, Octa Core, 2.86 GHz Processor                1
Exynos 2100, Octa Core, 2.9 GHz Processor               1
Snapdragon 675, Octa Core, 2 GHz Processor              1
Snapdragon  662 , Octa Core, 2 GHz Processor            1
Exynos 9810, Octa Core, 2.8 GHz Processor               1
Exynos 1330, Octa Core Processor                        1
Snapdragon  778G+, Octa Core Processor                  1
Snapdragon 680 , Octa Core, 2.4 GHz Processor           1
Helio   G90T , Octa Core, 2.05 GHz Processor            1
(28 nm), Quad Core, 1.5 GHz Processor                   1
Kirin  810, Octa Core, 2.2 GHz Processor                1
Snapdragon 439, Octa Core, 1.95 GHz Processor           1
Helio  P65 , Octa Core, 2 GHz Processor                 1
Helio P70, Octa Core, 2 GHz Processor                   1
Samsung Exynos 7885, Octa Core, 2.2 GHz Processor       1
Qualcomm Snapdragon 670, Octa Core, 2 GHz Processor     1
Qualcomm Snapdragon 625, Octa Core, 2 GHz Processor     1
Snapdragon  7 Gen2, Octa Core Processor                 1
Snapdragon  7 Gen1, Octa Core, 2.4 GHz Processor        1
Kirin 659, Octa Core, 2.36 GHz Processor                1
Helio  G88, Octa Core, 2 GHz Processor                  1
Snapdragon  690 , Octa Core, 2 GHz Processor            1
Dimensity 1000+, Octa Core, 2.6 GHz Processor           1
Spreadtrum  SC9832E , Quad Core, 1.4 GHz Processor      1
Snapdragon 665, Octa Core, 2 GHz Processor              1
Snapdragon 425, Quad Core, 1.2 GHz Processor            1
Spreadtrum  SC9832E, Quad Core, 1.4 GHz Processor       1
Google  Tensor 3, Octa Core Processor                   1
Name: count, dtype: int64

In [60]:
df["ram"].value_counts()

ram
8 GB RAM, 128 GB inbuilt     267
6 GB RAM, 128 GB inbuilt     190
4 GB RAM, 64 GB inbuilt      143
12 GB RAM, 256 GB inbuilt     70
8 GB RAM, 256 GB inbuilt      70
4 GB RAM, 128 GB inbuilt      62
3 GB RAM, 32 GB inbuilt       37
6 GB RAM, 64 GB inbuilt       29
2 GB RAM, 32 GB inbuilt       24
3 GB RAM, 64 GB inbuilt       15
12 GB RAM, 512 GB inbuilt     10
6 GB RAM, 256 GB inbuilt       7
16 GB RAM, 256 GB inbuilt      6
1 GB RAM, 16 GB inbuilt        6
4 GB RAM, 32 GB inbuilt        6
12 GB RAM, 128 GB inbuilt      4
2 GB RAM, 64 GB inbuilt        4
2 GB RAM, 16 GB inbuilt        4
6 GB RAM, 512 GB inbuilt       4
6 GB RAM, 1 TB inbuilt         4
16 GB RAM, 512 GB inbuilt      3
4 GB RAM, 256 GB inbuilt       3
3 GB RAM, 16 GB inbuilt        2
64 GB inbuilt                  2
8 GB RAM, 512 GB inbuilt       2
18 GB RAM, 512 GB inbuilt      1
512 MB RAM, 4 GB inbuilt       1
18 GB RAM, 256 GB inbuilt      1
512 GB inbuilt                 1
64 MB RAM, 128 MB inbuilt      1
4 GB RAM, 512 GB inbuilt       1
1 GB RAM, 8 GB inbuilt         1
12 GB RAM, 1 TB inbuilt        1
Name: count, dtype: int64

In [61]:
df["battery"].value_counts()

battery
5000 mAh Battery with 33W Fast Charging      103
5000 mAh Battery with 18W Fast Charging       89
5000 mAh Battery                              74
5000 mAh Battery with 67W Fast Charging       30
5000 mAh Battery with 10W Fast Charging       28
5000 mAh Battery with 15W Fast Charging       24
5000 mAh Battery with 25W Fast Charging       23
5000 mAh Battery with 120W Fast Charging      21
5000 mAh Battery with 80W Fast Charging       19
6000 mAh Battery with 18W Fast Charging       19
5000 mAh Battery with Fast Charging           18
5000 mAh Battery with 30W Fast Charging       15
4500 mAh Battery with 33W Fast Charging       14
6000 mAh Battery with 15W Fast Charging       13
4500 mAh Battery with 65W Fast Charging       12
4000 mAh Battery                              12
4500 mAh Battery with 25W Fast Charging       12
4500 mAh Battery with 80W Fast Charging       12
4500 mAh Battery with 67W Fast Charging       11
4700 mAh Battery with 80W Fast Charging        9
5000 mAh Battery with 44W Fast Charging        8
4700 mAh Battery with 66W Fast Charging        7
4230 mAh Battery                               7
5000 mAh Battery with 65W Fast Charging        6
5000 mAh Battery with 20W Fast Charging        6
6000 mAh Battery with 65W Fast Charging        6
4300 mAh Battery with 30W Fast Charging        6
4000 mAh Battery with 33W Fast Charging        6
5000 mAh Battery with 45W Fast Charging        6
4800 mAh Battery with 150W Fast Charging       5
4500 mAh Battery with Fast Charging            5
4600 mAh Battery with 66W Fast Charging        5
4700 mAh Battery with 120W Fast Charging       5
5020 mAh Battery with 18W Fast Charging        5
5080 mAh Battery with 67W Fast Charging        5
4500 mAh Battery with 66W Fast Charging        4
6000 mAh Battery with 25W Fast Charging        4
4300 mAh Battery with 44W Fast Charging        4
5500 mAh Battery with 67W Fast Charging        4
5020 mAh Battery with 33W Fast Charging        4
4800 mAh Battery with 66W Fast Charging        4
6000 mAh Battery                               4
6000 mAh Battery with 33W Fast Charging        4
4323 mAh Battery with Fast Charging            4
4500 mAh Battery with 45W Fast Charging        4
5000 mAh Battery with 100W Fast Charging       4
4000 mAh Battery with Fast Charging            4
4500 mAh Battery with 120W Fast Charging       4
3000 mAh Battery                               4
4400 mAh Battery with 66W Fast Charging        3
4400 mAh Battery with 25W Fast Charging        3
4600 mAh Battery with 120W Fast Charging       3
4050 mAh Battery with 44W Fast Charging        3
7000 mAh Battery with 33W Fast Charging        3
4800 mAh Battery with 67W Fast Charging        3
3700 mAh Battery with 25W Fast Charging        3
3500 mAh Battery                               3
3095 mAh Battery with Fast Charging            3
3200 mAh Battery with Fast Charging            3
4352 mAh Battery with Fast Charging            3
4030 mAh Battery                               3
4520 mAh Battery with 33W Fast Charging        3
4500 mAh Battery with 44W Fast Charging        3
3240 mAh Battery with Fast Charging            3
4980 mAh Battery with 120W Fast Charging       3
3279 mAh Battery with Fast Charging            3
4325 mAh Battery with Fast Charging            3
5000 mAh Battery with 66W Fast Charging        3
4250 mAh Battery with 33W Fast Charging        3
4500 mAh Battery with 60W Fast Charging        3
4000 mAh Battery with 15W Fast Charging        3
4000 mAh Battery with 25W Fast Charging        3
4300 mAh Battery with 65W Fast Charging        3
4300 mAh Battery with 66W Fast Charging        3
4000 mAh Battery with 66W Fast Charging        3
6000 mAh Battery with 44W Fast Charging        3
5000 mAh Battery with 22.5W Fast Charging      3
4350 mAh Battery with 120W Fast Charging       2
3360 mAh Battery                               2
4200 mAh Battery with 65W Fast Charging        2
4000 mAh Battery with 18W Fast Charging        2
5050 mAh Battery with 18W Fast Charging        2
4500 mAh Battery with 30W Fast Charging        2
4000 mAh Battery with 21W Fast Charging        2
3300 mAh Battery                               2
5160 mAh Battery with 67W Fast Charging        2
4410 mAh Battery with Fast Charging            2
5160 mAh Battery with 45W Fast Charging        2
4200 mAh Battery with 33W Fast Charging        2
4610 mAh Battery with 125W Fast Charging       2
6000 mAh Battery with Fast Charging            2
3020 mAh Battery                               2
4500 mAh Battery with 100W Fast Charging       2
4200 mAh Battery with 44W Fast Charging        2
6000 mAh Battery with 20W Fast Charging        2
3500 mAh Battery with Fast Charging            2
5003 mAh Battery with 30W Fast Charging        2
4700 mAh Battery with 67W Fast Charging        2
3110 mAh Battery                               2
4830 mAh Battery with 66W Fast Charging        2
4020 mAh Battery with 33W Fast Charging        2
4400 mAh Battery with 68W Fast Charging        2
4200 mAh Battery with 40W Fast Charging        2
4500 mAh Battery with 150W Fast Charging       2
4200 mAh Battery with 55W Fast Charging        2
4450 mAh Battery with 125W Fast Charging       2
4000 mAh Battery with 10W Fast Charging        2
4500 mAh Battery with 18W Fast Charging        2
4300 mAh Battery with 25W Fast Charging        2
2438 mAh Battery with Fast Charging            1
5100 mAh Battery with 40W Fast Charging        1
4600 mAh Battery with 125W Fast Charging       1
4200 mAh Battery with 120W Fast Charging       1
2150 mAh Battery                               1
3060 mAh Battery with Fast Charging            1
4300 mAh Battery with 120W Fast Charging       1
4355 mAh Battery with 30W Fast Charging        1
6000 mAh Battery with 80W Fast Charging        1
4800 mAh Battery with 68W Fast Charging        1
4520 mAh Battery with 67W Fast Charging        1
2800 mAh Battery                               1
4352 mAh Battery with 25W Fast Charging        1
5200 mAh Battery with 33W Fast Charging        1
3900 mAh Battery with 25W Fast Charging        1
4820 mAh Battery with 120W Fast Charging       1
4310 mAh Battery with 50W Fast Charging        1
4810 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 100W Fast Charging       1
5200 mAh Battery with 210W Fast Charging       1
4700 mAh Battery with 45W Fast Charging        1
4700 mAh Battery with 200W Fast Charging       1
5200 mAh Battery with 67W Fast Charging        1
2050 mAh Battery with Fast Charging            1
4500 mAh Battery with 180W Fast Charging       1
4614 mAh Battery with 30W Fast Charging        1
4450 mAh Battery                               1
3300 mAh Battery with 15W Fast Charging        1
5000 mAh Battery with 19W Fast Charging        1
2275 mAh Battery                               1
4860 mAh Battery with 67W Fast Charging        1
5160 mAh Battery with 33W Fast Charging        1
4870 mAh Battery with 120W Fast Charging       1
1900 mAh Battery                               1
4050 mAh Battery with 40W Fast Charging        1
4700 mAh Battery with 33W Fast Charging        1
4100 mAh Battery with 15W Fast Charging        1
3520 mAh Battery with Fast Charging            1
1500 mAh Battery                               1
6000 mAh Battery with 45W Fast Charging        1
4730 mAh Battery with 80W Fast Charging        1
4470 mAh Battery with 18W Fast Charging        1
5600 mAh Battery with 68W Fast Charging        1
5050 mAh Battery with 10W Fast Charging        1
4300 mAh Battery with 210W Fast Charging       1
5000 mAh Battery with 60W Fast Charging        1
4080 mAh Battery with 18W Fast Charging        1
5000 mAh Battery with 135W Fast Charging       1
5000 mAh Battery with 165W Fast Charging       1
2800 mAh Battery with Fast Charging            1
4300 mAh Battery with 33W Fast Charging        1
4200 mAh Battery with 66W Fast Charging        1
21000 mAh Battery with 33W Fast Charging       1
6000 mAh Battery with 120W Fast Charging       1
4700 mAh Battery with Fast Charging            1
4600 mAh Battery with 240W Fast Charging       1
5100 mAh Battery with 45W Fast Charging        1
1821 mAh Battery with 18W Fast Charging        1
4500 mAh Battery with 50W Fast Charging        1
1150 mAh Battery                               1
9800 mAh Battery with 66W Fast Charging        1
3500 mAh Battery with 18W Fast Charging        1
2230 mAh Battery                               1
4500 mAh Battery with 20W Fast Charging        1
4800 mAh Battery with 125W Fast Charging       1
4000 mAh Battery with 45W Fast Charging        1
4015 mAh Battery with 30W Fast Charging        1
4300 mAh Battery with 45W Fast Charging        1
4020 mAh Battery with 68W Fast Charging        1
3285 mAh Battery with Fast Charging            1
4300 mAh Battery with 67W Fast Charging        1
5100 mAh Battery with 120W Fast Charging       1
4300 mAh Battery with Fast Charging            1
4000 mAh Battery with 20W Fast Charging        1
4000 mAh Battery with 30W Fast Charging        1
4000 mAh Battery with 22.5W Fast Charging      1
4830 mAh Battery with 67W Fast Charging        1
5020 mAh Battery with 67W Fast Charging        1
4800 mAh Battery with 25W Fast Charging        1
3700 mAh Battery with Fast Charging            1
4200 mAh Battery with 67W Fast Charging        1
3315 mAh Battery                               1
5080 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 18W Fast Charging        1
5050 mAh Battery                               1
4800 mAh Battery                               1
4360 mAh Battery with 66W Fast Charging        1
4310 mAh Battery with 30W Fast Charging        1
4800 mAh Battery with 33W Fast Charging        1
3600 mAh Battery with 18W Fast Charging        1
7000 mAh Battery with Fast Charging            1
2000 mAh Battery                               1
3100 mAh Battery with 15W Fast Charging        1
4100 mAh Battery                               1
22000 mAh Battery with 33W Fast Charging       1
7000 mAh Battery                               1
5020 mAh Battery with 22.5W Fast Charging      1
5000 mAh Battery with 40W Fast Charging        1
7000 mAh Battery with 18W Fast Charging        1
2400 mAh Battery                               1
4350 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 27W Fast Charging        1
3200 mAh Battery                               1
2500 mAh Battery                               1
3700 mAh Battery with 18W Fast Charging        1
4532 mAh Battery with Fast Charging            1
3000 mAh Battery with 10W Fast Charging        1
5050 mAh Battery with 30W Fast Charging        1
5065 mAh Battery with 67W Fast Charging        1
4620 mAh Battery with 18W Fast Charging        1
4100 mAh Battery with 33W Fast Charging        1
4780 mAh Battery with 30W Fast Charging        1
3730 mAh Battery with Fast Charging            1
4500 mAh Battery with 55W Fast Charging        1
3400 mAh Battery with Fast Charging            1
2730 mAh Battery                               1
5180 mAh Battery with 10W Fast Charging        1
4500 mAh Battery with 68W Fast Charging        1
8000 mAh Battery                               1
5000 mAh Battery with 68W Fast Charging        1
5000 mAh Battery with 68.2W Fast Charging      1
Name: count, dtype: int64

In [62]:
df["display"].value_counts()

display
6.67 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          54
6.5 inches, 720 x 1600 px Display with Water Drop Notch              36
6.7 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           25
6.52 inches, 720 x 1600 px Display with Water Drop Notch             23
6.5 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            22
6.51 inches, 720 x 1600 px Display with Water Drop Notch             21
6.43 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole           19
6.43 inches, 1080 x 2400 px Display with Punch Hole                  16
6.62 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          15
6.53 inches, 720 x 1600 px Display with Water Drop Notch             14
6.4 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            14
6.55 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole          11
6.7 inches, 1440 x 3216 px, 120 Hz Display with Punch Hole           10
6.7 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.5 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       10
6.58 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch    10
6.5 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           10
6.6 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            10
6.78 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           9
6.6 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch       9
6.55 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            9
6.67 inches, 1080 x 2400 px Display with Punch Hole                   9
6.6 inches, 1080 x 2408 px Display with Water Drop Notch              9
6.7 inches, 1080 x 2400 px Display with Punch Hole                    8
6.58 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      8
6.6 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch      7
6.5 inches, 720 x 1600 px, 90 Hz Display with Punch Hole              7
6.6 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole            7
6.58 inches, 1080 x 2408 px Display with Water Drop Notch             7
6.53 inches, 1080 x 2340 px Display with Water Drop Notch             7
6.58 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      7
6.67 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           7
6.59 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           7
6.1 inches, 1170 x 2532 px Display with Small Notch                   6
6.4 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       6
6.73 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           6
6.44 inches, 1080 x 2400 px Display with Water Drop Notch             6
6.67 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           5
6.56 inches, 720 x 1612 px Display with Water Drop Notch              5
6.1 inches, 1170 x 2532 px Display with Large Notch                   5
6.8 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            5
6.6 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            5
6.5 inches, 720 x 1560 px Display with Water Drop Notch               5
6.4 inches, 1080 x 2400 px Display with Punch Hole                    5
6.44 inches, 1080 x 2404 px, 90 Hz Display with Water Drop Notch      5
6.56 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch       5
6.4 inches, 1080 x 2340 px Display with Water Drop Notch              5
6.67 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           5
6.35 inches, 720 x 1544 px Display with Water Drop Notch              4
6.6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            4
6.7 inches, 1290 x 2796 px, 120 Hz Display                            4
6.78 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           4
6.7 inches, 720 x 1600 px Display with Water Drop Notch               4
6.56 inches, 720 x 1600 px Display with Water Drop Notch              4
6.67 inches, 2400 x 1080 px, 120 Hz Display with Punch Hole           4
6.5 inches, 1600 x 720 px Display with Water Drop Notch               4
6.7 inches, 1080 x 2400 px Display with Water Drop Notch              4
6.56 inches, 1080 x 2376 px, 120 Hz Display with Punch Hole           4
6.6 inches, 720 x 1612 px, 90 Hz Display with Water Drop Notch        4
6.78 inches, 1080 x 2448 px, 165 Hz Display                           4
6.8 inches, 1440 x 3080 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2408 px, 90 Hz Display with Water Drop Notch      3
6.2 inches, 720 x 1520 px Display with Water Drop Notch               3
6.47 inches, 1080 x 2400 px Display with Punch Hole                   3
6.1 inches, 1179 x 2556 px, 120 Hz Display                            3
6.1 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.44 inches, 1080 x 2408 px Display with Water Drop Notch             3
6.7 inches, 2400 x 1080 px Display with Punch Hole                    3
6.8 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            3
6.6 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        3
6.43 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           3
6.73 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           3
6.4 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            3
6.78 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole           3
6.7 inches, 1284 x 2778 px, 120 Hz Display with Small Notch           3
6.44 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      3
6.51 inches, 1600 x 720 px Display with Punch Hole                    3
6.6 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole             3
6.7 inches, 1284 x 2778 px Display with Small Notch                   3
6.1 inches, 1170 x 2532 px, 120 Hz Display with Large Notch           3
8.03 inches, 1916 x 2160 px, 120 Hz Display                           3
7.1 inches, 1792 x 1920 px, 120 Hz Display with Punch Hole            3
6.6 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            3
6.6 inches, 2460 x 1080 px, 90 Hz Display with Punch Hole             3
5.4 inches, 1080 x 2340 px Display                                    3
6.59 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            3
6.6 inches, 720 x 1600 px Display with Water Drop Notch               3
6.44 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     3
6.8 inches, 1080 x 2460 px Display with Punch Hole                    3
4.7 inches, 750 x 1334 px Display                                     3
6.8 inches, 1116 x 2480 px, 120 Hz Display                            3
6.6 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole             3
6.78 inches, 1440 x 3200 px, 144 Hz Display with Punch Hole           3
5 inches, 854 x 480 px Display                                        3
6.4 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      2
6 inches, 1080 x 2160 px Display                                      2
6.4 inches, 1080 x 2340 px Display with Punch Hole                    2
6.22 inches, 720 x 1520 px Display with Water Drop Notch              2
6.22 inches, 1520 x 720 px Display with Water Drop Notch              2
6.5 inches, 1080 x 2400 px Display with Punch Hole                    2
6.1 inches, 828 x 1792 px Display with Large Notch                    2
6.6 inches, 1612 x 720 px Display with Water Drop Notch               2
6.78 inches, 1260 x 2800 px, 120 Hz Display with Punch Hole           2
6.8 inches, 1440 x 3040 px Display with Punch Hole                    2
6.6 inches, 2408 x 1080 px Display with Water Drop Notch              2
6.73 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.28 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.7 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Small Notch           2
6.58 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.73 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole             2
6.57 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           2
6 inches, 720 x 1440 px Display                                       2
6.3 inches, 1080 x 2340 px Display with Water Drop Notch              2
6.58 inches, 1080 x 2408 px, 90 Hz Display with Punch Hole            2
6.44 inches, 1080 x 2400 px, 90 Hz Display with Dual Punch Hole       2
6.49 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            2
6.7 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole             2
6.7 inches, 1080 x 2640 px, 120 Hz Display with Punch Hole            2
6.6 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.71 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole           2
6.56 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.56 inches, 1080 x 2376 px, 90 Hz Display with Small Notch           2
6.5 inches, 720 x 1600 px Display with Punch Hole                     2
5.5 inches, 1080 x 1920 px Display                                    2
6.18 inches, 1080 x 2246 px Display with Large Notch                  2
6.71 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole           2
6.4 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch        2
6.82 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       2
6.1 inches, 1080 x 2520 px, 120 Hz Display                            2
6.51 inches, 720 x 1600 px Display with Punch Hole                    2
6.8 inches, 1080 x 2460 px Display                                    2
6.71 inches, 720 x 1650 px Display with Water Drop Notch              2
5.45 inches, 720 x 1440 px Display                                    2
6.6 inches, 1080 x 2412 px, 144 Hz Display with Punch Hole            2
6.8 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            2
6.67 inches, 1220 x 2712 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1644 x 3840 px, 120 Hz Display                            2
6.44 inches, 1080 x 2400 px Display with Small Notch                  2
6.5 inches, 720 x 1560 px Display with Small Notch                    2
7.6 inches, 1812 x 2176 px, 120 Hz Display with Punch Hole            2
6.72 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           2
6.5 inches, 1080 x 2400 px Display with Water Drop Notch              2
6.55 inches, 720 x 1612 px Display with Water Drop Notch              2
6.8 inches, 1440 x 3088 px, 120 Hz Display with Punch Hole            1
6.67 inches, 1080 x 2340 px, 144 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2412 px, 120 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch     1
6.8 inches, 1080 x 2400 px, 165 Hz Display                            1
6.51 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.4 inches, 720 x 1600 px Display with Water Drop Notch               1
6.34 inches, 1080 x 2400 px Display with Punch Hole                   1
6.5 inches, 1600 x 720 px, 90 Hz Display with Punch Hole              1
6.09 inches, 1520 x 720 px Display with Water Drop Notch              1
6.67 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole            1
6.5 inches, 720 x 1544 px Display with Water Drop Notch               1
6.5 inches, 1440 x 3168 px Display with Water Drop Notch              1
6.53 inches, 1176 x 2400 px Display with Large Notch                  1
6.4 inches, 720 x 1560 px Display with Punch Hole                     1
6.1 inches, 1560 x 720 px Display with Water Drop Notch               1
6.55 inches, 1612 x 720 px, 90 Hz Display with Water Drop Notch       1
6.83 inches, 1200 x 2860 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1200 x 2400 px, 120 Hz Display with Punch Hole            1
5.7 inches, 1080 x 2280 px Display                                    1
6.4 inches, 1440 x 3040 px Display with Punch Hole                    1
6.2 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.8 inches, 1080 x 2520 px, 120 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2400 px Display with Punch Hole                   1
6.73 inches, 1290 x 2796 px, 120 Hz Display                           1
6.71 inches, 1440 x 3214 px, 120 Hz Display with Punch Hole           1
6.6 inches, 1600 x 720 px Display with Punch Hole                     1
6 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole              1
6.81 inches, 1080 x 2388 px Display                                   1
7.8 inches, 1440 x 1920 px Display                                    1
6.82 inches, 720 x 1640 px, 90 Hz Display with Punch Hole             1
6.5 inches, 720 x 1600 px, 120 Hz Display with Punch Hole             1
6.53 inches, 720 x 1600 px, 90 Hz Display with Punch Hole             1
6.2 inches, 1520 x 720 px Display with Water Drop Notch               1
6.8 inches, 1080 x 2448 px, 165 Hz Display                            1
6.81 inches, 1080 x 2400 px Display with Punch Hole                   1
4.7 inches, 1080 x 1920 px Display                                    1
6.06 inches, 1170 x 2532 px, 120 Hz Display with Punch Hole           1
6.82 inches, 720 x 1640 px, 90 Hz Display with Water Drop Notch       1
5.9 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole            1
6.3 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
6.7 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch       1
6.9 inches, 1080 x 2460 px, 120 Hz Display with Punch Hole            1
6.1 inches, 828 x 1792 px Display                                     1
5.4 inches, 1080 x 2340 px Display with Large Notch                   1
6.9 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole             1
5.42 inches, 1080 x 2340 px Display with Punch Hole                   1
6.36 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.2 inches, 720 x 1680 px Display                                     1
7.92 inches, 2088 x 2250 px Display                                   1
6.52 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.82 inches, 1640 x 720 px, 90 Hz Display with Punch Hole             1
4.5 inches, 480 x 854 px Display                                      1
8.03 inches, 1916 x 2160 px, 120 Hz Display with Punch Hole           1
6.74 inches, 1212 x 2616 px, 120 Hz Display                           1
2.8 inches, 240 x 320 px Display                                      1
6.66 inches, 720 x 1600 px, 90 Hz Display with Water Drop Notch       1
6.67 inches, 1080 x 2160 px, 90 Hz Display with Punch Hole            1
6.8 inches, 1080 x 2400 px, 120 Hz Display                            1
6.64 inches, 1080 x 2388 px, 120 Hz Display with Punch Hole           1
6.67 inches, 1080 x 2340 px, 120 Hz Display with Punch Hole           1
6.28 inches, 1080 x 2280 px Display                                   1
6 inches, 1440 x 2880 px Display                                      1
6 inches, 1080 x 2340 px, 90 Hz Display with Punch Hole               1
6.73 inches, 1440 x 3412 px, 144 Hz Display with Punch Hole           1
6.58 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.56 inches, 720 x 1612 px, 90 Hz Display with Punch Hole             1
6.8 inches, 1080 x 2460 px, 144 Hz Display with Punch Hole            1
6.62 inches, 2408 x 1080 px Display with Punch Hole                   1
6.74 inches, 720 x 1600 px Display with Water Drop Notch              1
3.54 inches, 640 x 960 px Display                                     1
6.67 inches, 1080 x 2412 px, 90 Hz Display with Punch Hole            1
6.9 inches, 1400 x 3200 px, 120 Hz Display with Punch Hole            1
6.55 inches, 1080 x 2400 px, 144 Hz Display with Punch Hole           1
6.6 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.5 inches, 1600 x 720 px, 90 Hz Display with Water Drop Notch        1
6.7 inches, 1440 x 3120 px, 120 Hz Display with Punch Hole            1
6.95 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.7 inches, 720 x 1650 px Display with Punch Hole                     1
8.02 inches, 1914 x 2160 px, 120 Hz Display with Punch Hole           1
6.78 inches, 1080 x 2388 px, 90 Hz Display with Punch Hole            1
6.92 inches, 1080 x 2460 px, 144 Hz Display                           1
6.51 inches, 1080 x 2408 px, 144 Hz Display with Punch Hole           1
6.2 inches, 1440 x 3200 px, 120 Hz Display with Punch Hole            1
6.43 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
6.78 inches, 1080 x 2448 px, 144 Hz Display                           1
7.6 inches, 1768 x 2208 px, 120 Hz Display with Punch Hole            1
6.58 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch     1
6.7 inches, 1080 x 2460 px, 165 Hz Display with Punch Hole            1
6.6 inches, 1080 x 2460 px, 90 Hz Display with Water Drop Notch       1
5.5 inches, 720 x 1440 px Display                                     1
6.9 inches, 1440 x 3200 px Display with Punch Hole                    1
6.5 inches, 1242 x 2688 px Display with Large Notch                   1
6.5 inches, 1080 x 2400 px, 120 Hz Display                            1
6.78 inches, 1080 x 2400 px, 120 Hz Display                           1
6.7 inches, 1080 x 2400 px, 120 Hz Display with Water Drop Notch      1
6.78 inches, 1080 x 2460 px, 90 Hz Display with Punch Hole            1
2.4 inches, 240 x 320 px Display                                      1
6.5 inches, 1644 x 3840 px Display                                    1
6.76 inches, 1344 x 2772 px, 90 Hz Display with Punch Hole            1
6.57 inches, 1080 x 2400 px, 120 Hz Display with Punch Hole           1
6.44 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole            1
6.76 inches, 1344 x 2772 px, 120 Hz Display with Punch Hole           1
6.67 inches, 2400 x 1080 px, 144 Hz Display with Punch Hole           1
6.8 inches, 1080 x 2460 px Display with Water Drop Notch              1
6.5 inches, 1080 x 2340 px Display                                    1
6.68 inches, 1284 x 2778 px, 120 Hz Display with Punch Hole           1
6.7 inches, 1080 x 2412 px, 120 Hz Display with Water Drop Notch      1
6.54 inches, 720 x 1560 px Display with Small Notch                   1
4.7 inches, 750 x 1334 px Display with Large Notch                    1
6.7 inches, 1080 x 2400 px, 165 Hz Display                            1
6.5 inches, 720 x 1600 px Display with Small Notch                    1
6.1 inches, 720 x 1560 px Display with Water Drop Notch               1
6.56 inches, 1080 x 2400 px, 90 Hz Display with Water Drop Notch      1
6.4 inches, 1080 x 2408 px Display with Water Drop Notch              1
6.91 inches, 1080 x 2460 px Display with Punch Hole                   1
6.82 inches, 720 x 1600 px Display with Water Drop Notch              1
7.4 inches, 1440 x 3200 px Display                                    1
6.43 inches, 1080 x 2400 px Display with Dual Punch Hole              1
6.38 inches, 1080 x 2340 px Display with Water Drop Notch             1
6.67 inches, 1080 x 2408 px, 120 Hz Display with Water Drop Notch     1
6.76 inches, 1440 x 3200 px, 120 Hz Display with Small Notch          1
7.8 inches, 2200 x 2480 px, 120 Hz Display with Punch Hole            1
6.73 inches, 1080 x 2448 px, 165 Hz Display                           1
6.14 inches, 1080 x 2400 px Display with Punch Hole                   1
6.1 inches, 1080 x 2400 px, 90 Hz Display with Punch Hole             1
5 inches, 720 x 1280 px Display                                       1
6.52 inches, 720 x 1560 px Display with Punch Hole                    1
6.62 inches, 1080 x 2412 px, 144 Hz Display with Water Drop Notch     1
6.06 inches, 1170 x 2532 px Display with Punch Hole                   1

In [63]:
df["camera"].value_counts()

camera
50 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   40
64 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   38
50 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   34
13 MP + 2 MP Dual Rear & 5 MP Front Camera                             23
50 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                    20
13 MP Rear & 5 MP Front Camera                                         20
12 MP + 12 MP Dual Rear & 12 MP Front Camera                           20
8 MP Rear & 5 MP Front Camera                                          19
50 MP + 2 MP Dual Rear & 8 MP Front Camera                             19
13 MP + 2 MP Dual Rear & 8 MP Front Camera                             18
108 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                  18
64 MP Quad Rear & 32 MP Front Camera                                   18
64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   16
50 MP + 2 MP Dual Rear & 5 MP Front Camera                             14
48 MP Quad Rear & 13 MP Front Camera                                   14
48 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   14
50 MP Quad Rear & 8 MP Front Camera                                    13
108 MP Quad Rear & 32 MP Front Camera                                  12
48 MP Quad Rear & 16 MP Front Camera                                   12
50 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                   11
12 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                 10
64 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                   10
108 MP Quad Rear & 16 MP Front Camera                                  10
13 MP + 2 MP + 2 MP Triple Rear & 5 MP Front Camera                    10
64 MP Quad Rear & 16 MP Front Camera                                   10
13 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     9
50 MP + 8 MP Dual Rear & 16 MP Front Camera                             9
13 MP Dual Rear & 8 MP Front Camera                                     9
64 MP Quad Rear & 20 MP Front Camera                                    8
8 MP Dual Rear & 5 MP Front Camera                                      8
48 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                  8
48 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     8
50 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                   7
50 MP + 2 MP Triple Rear & 16 MP Front Camera                           7
50 MP Dual Rear & 8 MP Front Camera                                     7
50 MP + 2 MP Triple Rear & 8 MP Front Camera                            6
50 MP Quad Rear & 16 MP Front Camera                                    6
48 MP Quad Rear & 8 MP Front Camera                                     6
108 MP Quad Rear & 40 MP Front Camera                                   6
50 MP + 2 MP Dual Rear & 16 MP Front Camera                             6
48 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                    6
50 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                  6
50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                   5
12 MP + 12 MP + 8 MP Triple Rear & 32 MP Front Camera                   5
64 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                  5
108 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                   5
64 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                    5
50 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                     5
64 MP + 8 MP + 5 MP Triple Rear & 32 MP Front Camera                    5
64 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                    5
13 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                    5
200 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                   5
50 MP Quad Rear & 32 MP Front Camera                                    5
50 MP Quad Rear & 13 MP Front Camera                                    4
5 MP Rear & 2 MP Front Camera                                           4
64 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                    4
64 MP + 8 MP + 2 MP Triple Rear & 44 MP Front Camera                    4
50 MP + 2 MP + 2 MP Triple Rear & 5 MP Front Camera                     4
108 MP + 2 MP Dual Rear & 16 MP Front Camera                            4
50 MP + 13 MP + 5 MP Triple Rear & 12 MP Front Camera                   4
200 MP + 50 MP + 12 MP Triple Rear & 60 MP Front Camera                 4
48 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                   4
50 MP + 12 MP + 10 MP Triple Rear & 10 MP Front Camera                  4
13 MP Rear & 8 MP Front Camera                                          4
64 MP Quad Rear & 13 MP Front Camera                                    4
50 MP + 8 MP Dual Rear & 32 MP Front Camera                             4
48 MP + 2 MP Dual Rear & 5 MP Front Camera                              3
48 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                    3
50 MP + 2 MP + 2 MP Triple Rear & 13 MP Front Camera                    3
50 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                     3
16 MP + 2 MP Dual Rear & 8 MP Front Camera                              3
48 MP + 2 MP Dual Rear & 8 MP Front Camera                              3
8 MP + Depth Sensor Dual Rear & 5 MP Front Camera                       3
50 MP + 48 MP + 8 MP Triple Rear & 32 MP Front Camera                   3
12 MP Rear & 7 MP Front Camera                                          3
50 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                   3
50 MP + 12 MP + 12 MP Triple Rear & 32 MP Front Camera                  3
16 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                    3
108 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                  3
48 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                    3
64 MP + 16 MP + 8 MP Triple Rear & 32 MP Front Camera                   3
50 MP + 8 MP + 2 MP Triple Rear & 13 MP Front Camera                    3
48 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                     3
50 MP + 50 MP Dual Rear & 16 MP Front Camera                            3
50 MP + Depth Sensor Dual Rear & 8 MP Front Camera                      3
8 MP + 0.3 MP Dual Rear & 5 MP Front Camera                             3
48 MP + 13 MP + 13 MP Triple Rear & 16 MP Front Camera                  3
50 MP + 0.3 MP Dual Rear & 5 MP Front Camera                            2
108 MP + 2 MP + 2 MP Triple Rear & 16 MP Front Camera                   2
12 MP + 8 MP + 8 MP Triple Rear & 8 MP Front Camera                     2
48 MP + 2 MP Dual Rear & 16 MP Front Camera                             2
16 MP + 5 MP Dual Rear & 25 MP Front Camera                             2
12 MP Quad Rear & 10 MP Front Camera                                    2
12.2 MP + 12 MP Dual Rear & 8 MP Front Camera                           2
50 MP + 12 MP + 12 MP Triple Rear & 12 MP Front Camera                  2
48 MP + 8 MP + 5 MP Triple Rear & 32 MP Front Camera                    2
108 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                   2
64 MP Quad Rear & 16 MP + 8 MP Dual Front Camera                        2
64 MP Quad Rear & 10 MP Front Camera                                    2
20 MP Rear & 13 MP Front Camera                                         2
13 MP Dual Rear & 5 MP Front Camera                                     2
64 MP + 8 MP + 2 MP Triple Rear & 50 MP + 8 MP Dual Front Camera        2
50 MP + 12 MP + 10 MP Triple Rear & 12 MP Front Camera                  2
50 MP + 13 MP + 8 MP Triple Rear & 16 MP Front Camera                   2
64 MP + 12 MP + 5 MP Triple Rear & 32 MP Front Camera                   2
108 MP + 8 MP + 2 MP Triple Rear & 50 MP + 8 MP Dual Front Camera       2
48 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                    2
8 MP + 0.08 MP Dual Rear & 5 MP Front Camera                            2
50 MP + 8 MP + 2 MP Triple Rear & 44 MP Front Camera                    2
64 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                    2
12 MP + 12 MP Dual Rear & 10 MP Front Camera                            2
50 MP + 50 MP + 12 MP Triple Rear & 60 MP Front Camera                  2
48 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                    2
16 MP + 12.2 MP Dual Rear & 8 MP Front Camera                           2
64 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                     2
12.2 MP Rear & 8 MP Front Camera                                        2
16 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     2
64 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                     2
13 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                    2
2 MP Rear Camera                                                        2
108 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                  2
50 MP + 50 MP + 13 MP Triple Rear & 32 MP Front Camera                  2
12 MP + 12 MP + 12 MP Triple Rear & 8 MP Front Camera                   2
50 MP + 5 MP + 2 MP Triple Rear & 16 MP Front Camera                    2
50 MP + 48 MP + 12 MP Triple Rear & 11.1 MP Front Camera                2
108 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                   2
64 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                   2
50 MP + Depth Sensor Dual Rear & 5 MP Front Camera                      2
50 MP + 12 MP + 10 MP Triple Rear & 10 MP + 4 MP Dual Front Camera      2
8 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front Camera                    2
54 MP + 50 MP + 2 MP Triple Rear & 32 MP Front Camera                   2
64 MP Quad Rear & 32 MP + 8 MP Dual Front Camera                        2
12 MP + 5 MP Dual Rear & 20 MP Front Camera                             2
64 MP + 12 MP + 5 MP Triple Rear & 10 MP Front Camera                   2
13 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                     2
50 MP + 48 MP + 32 MP Triple Rear & 16 MP Front Camera                  2
200 MP Quad Rear & 12 MP Front Camera                                   1
50 MP + 12 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 13 MP Dual Rear & 16 MP Front Camera                            1
50 MP + 8 MP + 2 MP Triple Rear & 60 MP Front Camera                    1
48 MP + 12 MP + 5 MP Triple Rear & 16 MP Front Camera                   1
50 MP Quad Rear & 48 MP + 8 MP Dual Front Camera                        1
48 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
13 MP Rear & 16 MP Front Camera                                         1
13 MP Rear & 13 MP Front Camera                                         1
13 MP + 2 MP Triple Rear & 8 MP Front Camera                            1
50 MP + 20 MP + 2 MP Triple Rear & 32 MP + 32 MP Dual Front Camera      1
50 MP + 12 MP Dual Rear & 16 MP Front Camera                            1
50 MP + 50 MP Triple Rear & 16 MP Front Camera                          1
200 MP Quad Rear & 16 MP Front Camera                                   1
48 MP + 8 MP + 2 MP Triple Rear & 32 MP Front Camera                    1
108 MP Quad Rear & 20 MP Front Camera                                   1
13 MP + 2 MP Dual Rear & 13 MP Front Camera                             1
64 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
16 MP + 12.2 MP Dual Rear & 8 MP + TOF 3D Dual Front Camera             1
16 MP + 12 MP + 12 MP Triple Rear & 10 MP + 8 MP Dual Front Camera      1
13 MP + Depth Sensor + Ultra Wide Triple Rear & 8 MP Front Camera       1
64 MP + 20 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
8 MP + 0.3 MP Dual Rear & 8 MP Front Camera                             1
200 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                 1
50 MP + 48 MP + 48 MP Triple Rear & 32 MP Front Camera                  1
13 MP Rear & 2.1 MP Front Camera                                        1
48 MP Quad Rear & 20 MP Front Camera                                    1
50 MP + 13 MP + 8 MP Triple Rear & 48 MP + 8 MP Dual Front Camera       1
50 MP + 12 MP Dual Rear & 12 MP Front Camera                            1
48 MP Triple Rear & 8 MP Front Camera                                   1
108 MP + 20 MP + 12 MP Triple Rear Camera                               1
64 MP + 50 MP Triple Rear & 16 MP Front Camera                          1
108 MP + 8 MP + 8 MP Triple Rear & 16 MP Front Camera                   1
2 MP Rear & 0.3 MP Front Camera                                         1
50 MP Quad Rear & 16 MP + 16 MP Dual Front Camera                       1
50 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 8 MP + 2 MP Triple Rear & 50 MP + 8 MP Dual Front Camera        1
50 MP + 12 MP Dual Rear & 8 MP Front Camera                             1
50.3 MP + 50 MP + 12 MP Triple Rear & 32 MP Front Camera                1
54 MP + 8 MP + 2 MP Triple Rear & 16 MP Front Camera                    1
200 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                   1
200 MP Quad Rear & 60 MP Front Camera                                   1
64 MP Quad Rear & 44 MP + 8 MP Dual Front Camera                        1
50 MP + 12 MP Dual Rear & 10.8 MP Front Camera                          1
108 MP + 13 MP + 2 MP Triple Rear & 60 MP Front Camera                  1
12 MP + 5 MP Dual Rear & 7 MP Front Camera                              1
108 MP + 2 MP Triple Rear & 16 MP Front Camera                          1
50 MP + 12 MP + 10 MP Triple Rear & 32 MP Front Camera                  1
50 MP + 48 MP + 13 MP Triple Rear & 13 MP Front Camera                  1
12 MP Quad Rear & 12 MP Front Camera                                    1
48 MP + 8 MP + 5 MP Triple Rear & 8 MP Front Camera                     1
20 MP + 16 MP Dual Rear & 16 MP Front Camera                            1
108 MP + 50 MP + 48 MP Triple Rear & 32 MP Front Camera                 1
64 MP + 64 MP + 64 MP Triple Rear & 16 MP Front Camera                  1
64 MP + 13 MP Dual Rear & 16 MP Front Camera                            1
200 MP Quad Rear & 32 MP Front Camera                                   1
64 MP + 13 MP + 5 MP Triple Rear & 24 MP Front Camera                   1
12 MP + 12 MP + 12 MP Triple Rear & 10 MP + 4 MP Dual Front Camera      1
64 MP + 13 MP + 12 MP Triple Rear & 32 MP Front Camera                  1
50 MP + 13 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
48 MP + 2 MP + 2 MP Triple Rear & 32 MP Front Camera                    1
64 MP + 12 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 50 MP + 16 MP Triple Rear & 16 MP Front Camera                  1
48 MP + 5 MP + 2 MP Triple Rear & 8 MP Front Camera                     1
48 MP + 16 MP + 2 MP Triple Rear & 16 MP Front Camera                   1
13 MP Rear & 7 MP Front Camera                                          1
64 MP + 20 MP + 2 MP Triple Rear & Main Front Camera                    1
200 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                  1
13 MP + Depth Sensor Dual Rear & 5 MP Front Camera                      1
8 MP Rear & 2 MP Front Camera                                           1
200 MP Penta Rear & 32 MP Front Camera                                  1
50 MP + 2 MP + 0.3 MP Triple Rear & 8 MP Front Camera                   1
64 MP + 5 MP + 2 MP Triple Rear & 16 MP Front Camera                    1
50 MP + 48 MP + 12 MP Triple Rear & 10.8 MP Front Camera                1
50 MP + 50 MP + 13 MP Triple Rear & 16 MP Front Camera                  1
50 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                   1
0.3 MP Rear Camera                                                      1
12 MP Quad Rear & 8 MP Front Camera                                     1
108 MP + 16 MP + 8 MP Triple Rear & 25 MP Front Camera                  1
50 MP + 13 MP + 12 MP Triple Rear & 16 MP Front Camera                  1
50 MP + 20 MP + 12 MP Triple Rear & 13 MP Dual Front Camera             1
50 MP Quad Rear & 13 MP Dual Front Camera                               1
64 MP + 2 MP Triple Rear & 16 MP Front Camera                           1
64 MP + 13 MP + 5 MP Triple Rear & 20 MP Front Camera                   1
64 MP + 13 MP + 0.3 MP Triple Rear & 10 MP Front Camera                 1
12 MP + 12 MP + 12 MP Triple Rear & 32 MP Front Camera                  1
64 MP + 50 MP + 8 MP Triple Rear & 16 MP Front Camera                   1
50 MP + 16 MP + 13 MP Triple Rear & 32 MP Front Camera                  1
50 MP + 50 MP + 2 MP Triple Rear & 60 MP Front Camera                   1
50 MP + 48 MP + 32 MP Triple Rear & 32 MP + 32 MP Dual Front Camera     1
64 MP + 16 MP + 12 MP Triple Rear & 16 MP Front Camera                  1
16 MP Rear & 13 MP Front Camera                                         1
13 MP Quad Rear & 8 MP Front Camera                                     1
48 MP Quad Rear & 16 MP + 2 MP Dual Front Camera                        1
48 MP Quad Rear & 32 MP Front Camera                                    1
64 MP + 13 MP Dual Rear & 32 MP Front Camera                            1
64 MP + 50 MP + 13 MP Triple Rear & 13 MP Front Camera                  1
50 MP + 13 MP + 8 MP Triple Rear & 10.7 MP Front Camera                 1
50 MP + 13 MP Dual Rear & 13 MP Front Camera                            1
5 MP + 0.3 MP Dual Rear & 5 MP Front Camera                             1
5 MP Rear & 5 MP Front Camera                                           1
64 MP + 8 MP + 2 MP Triple Rear & 44 MP + 8 MP Dual Front Camera        1
50.3 MP Quad Rear & 32 MP Front Camera                                  1
50 MP + 0.3 MP Dual Rear & 8 MP Front Camera                            1
50.3 MP + 50 MP + 50 MP Triple Rear & 32 MP Front Camera                1
64 MP + 13 MP + 2 MP Triple Rear & 32 MP Front Camera                   1
50 MP + 8 MP + 2 MP Triple Rear & 50 MP Front Camera                    1
Foldable Display, Dual Display                                          1
108 MP + 13 MP + 5 MP Triple Rear & 20 MP Front Camera                  1
48 MP Quad Rear & 32 MP + 8 MP Dual Front Camera                        1
13 MP + 8 MP + 2 MP Triple Rear & 8 MP Front Camera                     1
50 MP + 8 MP + 2 MP Triple Rear & 20 MP Front Camera                    1
200 MP + 50 MP + 8 MP Triple Rear & 50 MP Front Camera                  1
12 MP Rear & 10.8 MP Front Camera                                       1
50 MP + 8 MP Dual Rear & 10.1 MP Front Camera                           1
50 MP + 50 MP + 50 MP Triple Rear & 20 MP Front Camera                  1
108 MP + 13 MP + 8 MP Triple Rear & 20 MP Front Camera                  1
50 MP Quad Rear & 32 MP Dual Front Camera                               1
13 MP + 2 MP Dual Rear & 20 MP Front Camera                             1
12 MP + 12 MP Dual Rear & 8 MP Front Camera                             1
64 MP + 13 MP + 2 MP Triple Rear & 50 MP Front Camera                   1
64 MP + 2 MP Dual Rear & 32 MP Front Camera                             1
47.2 MP + 1.9 MP Dual Rear & 12.6 MP Front Camera                       1
64 MP + 2 MP Dual Rear & 16 MP Front Camera                             1
48 MP + 2 MP Triple Rear & 32 MP Front Camera                           1
50 MP + 3 MP + 2 MP Triple Rear & 8 MP Front Camera                     1
50 MP + 13 MP + 5 MP Triple Rear & 32 MP Front Camera                   1
64 MP + 8 MP + 5 MP Triple Rear & 16 MP Front Camera                    1
108 MP + 8 MP + 5 MP Triple Rear & 20 MP Front Camera                   1
64 MP + 16 MP Dual Rear & 20 MP Front Camera                            1
12 MP + 2 MP + 2 MP Triple Rear & 8 MP Front Camera                     1
12 MP + 2 MP Dual Rear & 8 MP Front Camera                              1
16 MP + 12 MP + 12 MP Triple Rear & 10 MP Front Camera                  1
13 MP + 2 MP Dual Rear & 16 MP Front Camera                             1

In [64]:
df["card"].value_counts()

card
Memory Card Not Supported              354
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported                   89
Memory Card Supported, upto 256 GB      89
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card Supported, upto 32 GB        4
Memory Card (Hybrid), upto 128 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Memory Card Supported, upto 1000 GB      1
Name: count, dtype: int64

In [65]:
brand_name=df["model"].str.split(" ").str.get(0)

In [66]:
df.insert(1,"brand_name",brand_name)

In [67]:
df["brand_name"].value_counts()

brand_name
Xiaomi       134
Samsung      132
Vivo         111
Realme        97
OPPO          62
Motorola      52
Apple         46
OnePlus       42
Tecno         33
iQOO          32
Infinix       29
Poco          28
Oppo          26
Huawei        16
Nokia         15
Google        14
POCO          13
Honor         13
Sony           9
itel           8
Asus           7
Nubia          6
Nothing        5
Jio            4
Lava           4
LG             3
Gionee         3
Redmi          3
Letv           3
Oukitel        3
Micromax       3
iKall          3
Doogee         2
ZTE            2
Lenovo         2
Itel           2
Royole         2
Lyf            2
Tesla          1
Duoqin         1
Cola           1
LeEco          1
BLU            1
Vertu          1
Leitz          1
CAT            1
TCL            1
Sharp          1
Blackview      1
Name: count, dtype: int64

In [68]:
temp_df=df[df["brand_name"]=="Oppo"]

In [69]:
df.loc[temp_df.index,"brand_name"]="OPPO"

In [70]:
temp_df=df[df["brand_name"]=="Poco"]

In [71]:
df.loc[temp_df.index,"brand_name"]="POCO"

In [72]:
temp_df=df[df["brand_name"]=="Itel"]

In [73]:
df.loc[temp_df.index,"brand_name"]="itel"

In [74]:
df["brand_name"].value_counts()

brand_name
Xiaomi       134
Samsung      132
Vivo         111
Realme        97
OPPO          88
Motorola      52
Apple         46
OnePlus       42
POCO          41
Tecno         33
iQOO          32
Infinix       29
Huawei        16
Nokia         15
Google        14
Honor         13
itel          10
Sony           9
Asus           7
Nubia          6
Nothing        5
Jio            4
Lava           4
Gionee         3
Letv           3
iKall          3
LG             3
Oukitel        3
Redmi          3
Micromax       3
Doogee         2
Lenovo         2
ZTE            2
Lyf            2
Royole         2
Tesla          1
LeEco          1
Duoqin         1
Cola           1
BLU            1
Vertu          1
Leitz          1
CAT            1
TCL            1
Sharp          1
Blackview      1
Name: count, dtype: int64

In [75]:
has_dual_sim=df["sim"].str.contains("Dual")
has_5g=df["sim"].str.contains("5G")
has_nfc=df["sim"].str.contains("NFC")
has_ir_blaster=df["sim"].str.contains("IR Blaster")

In [76]:
df.insert(6,"has_dual_sim",has_dual_sim)
df.insert(7,"has_5g",has_5g)
df.insert(8,"has_nfc",has_nfc)
df.insert(9,"has_ir_blaster",has_ir_blaster)

In [77]:
processor_name=df["processor"].str.split(",").str.get(0)
num_cores=df["processor"].str.split(",").str.get(1)
processor_speed=df["processor"].str.split(",").str.get(2)

In [78]:
df.insert(10,"processor_name",processor_name)
df.insert(11,"num_cores",num_cores)
df.insert(12,"processor_speed",processor_speed)

In [79]:
df["processor_name"].value_counts()

processor_name
Dimensity 700 5G           29
Helio P35                  28
Snapdragon 8+ Gen1         26
Snapdragon 8 Gen2          23
Snapdragon 695             23
Snapdragon 680             23
Helio G35                  20
Snapdragon  680            18
Snapdragon  8 Gen1         18
Snapdragon 8 Gen1          17
Bionic A15                 16
Snapdragon  695            16
Dimensity  810 5G          15
Snapdragon 870             15
Helio G96                  15
Helio G80                  14
Helio G99                  14
Snapdragon 778G            12
Dimensity 1080             12
Snapdragon  8+ Gen1        12
Dimensity 810 5G           12
Dimensity  920 5G          11
Snapdragon 888             11
Helio G37                  11
Helio  G85                 10
Snapdragon  888            10
Helio A22                  10
Helio G95                  10
Bionic  A16                10
Helio G25                  10
Tiger T612                  9
Octa Core Processor         9
Helio G88                   8
Snapdragon 720G             8
Dimensity 1300              8
Bionic A14                  8
Snapdragon  870             7
Snapdragon 865              7
Quad Core                   6
Exynos 850                  6
Dimensity 8100 Max          6
Snapdragon  7 Gen1          6
Helio G85                   6
Helio  G96                  6
Helio P22                   6
Dimensity 9000 Plus         6
Unisoc  T606                6
A13 Bionic                  5
Snapdragon  732G            5
Octa Core                   5
Snapdragon  778G            5
Dimensity 1200              5
Exynos  2100                5
Dimensity 8200              5
Snapdragon  695             5
Dimensity 700               5
Dimensity 900               5
Snapdragon 778G Plus        5
Unisoc  SC9863A             5
Dimensity  8100             5
Snapdragon 695              5
Snapdragon 4 Gen 1          4
Dimensity 9000              4
Dimensity 800U              4
Snapdragon 778G+            4
Snapdragon  778G            4
Exynos  1280                4
Exynos 1280                 4
Dimensity 720               4
Exynos 1330                 4
Google  Tensor              4
Snapdragon  480             4
Exynos 990                  4
Dimensity 810               3
Dimensity  900              3
Dimensity 9200              3
Helio  G99                  3
Snapdragon 888+             3
Snapdragon 7 Gen1           3
 Snapdragon  695            3
Snapdragon  8 Gen2          3
Dimensity  700 5G           3
Dimensity 8100-Max          3
Exynos  850                 3
Tiger  T616                 3
Helio  G25                  3
Exynos 9825                 3
Helio P60                   3
Snapdragon  665             3
Snapdragon 439              3
Snapdragon 845              3
Exynos  990                 3
Snapdragon  865             3
Tiger T610                  3
Snapdragon  888+            3
Qualcomm 215                3
Snapdragon 765G             3
Dimensity  930              3
Snapdragon 480+             3
Dimensity  1300             3
Snapdragon 765G             3
Dimensity  8200             2
Snapdragon 6 Gen 1          2
Snapdragon  4 Gen 1         2
Dimensity 700               2
Tiger  T310                 2
Dimensity  900 5G           2
Unisoc T612                 2
Snapdragon 712              2
Dimensity 920 5G            2
Dimensity 800U              2
Snapdragon  480+            2
Bionic A16                  2
SC9863A                     2
Snapdragon 732G             2
Helio                       2
Snapdragon  750G            2
Helio G70                   2
Helio P95                   2
Helio P70                   2
Snapdragon 460              2
Kirin  990                  2
Exynos 9810                 2
Snapdragon  750G            2
Snapdragon  439             2
Snapdragon  675             2
Snapdragon 865              2
Snapdragon  888             2
Exynos 9611                 2
Unisoc SC9863A              2
Dimensity  9000             2
Snapdragon  778G Plus       2
Snapdragon 662              2
Helio G85                   2
Dimensity 8100              2
Snapdragon 855+             2
Bionic  A15                 2
Snapdragon 678              2
Unisoc  T610                2
Unisoc  SC9863a             2
Snapdragon 690              2
Snapdragon  765G            2
Snapdragon  720G            2
Helio P35                   2
Snapdragon 425              2
Tiger T616                  2
Exynos 9820                 2
Tiger T700                  1
Tiger T310                  1
Tiger T7150                 1
Unisoc  SC9836A             1
Google Tensor               1
Dimensity  1200 Max         1
Snapdragon  8+ Gen1         1
Google Tensor G2            1
Dimensity 930               1
Exynos  2300                1
Apple  A13                  1
Google  Tensor G2           1
Exynos 1380                 1
Helio  P22                  1
Snapdragon 460              1
 Snapdragon 695             1
Exynos 1200                 1
Unisoc T606                 1
Helio  G95                  1
Snapdragon  720G            1
Helio  P35                  1
Snapdragon 860              1
Snapdragon 801              1
Snapdragon 775              1
Snapdragon  810             1
Bionic  A17                 1
Spreadtrum  SC7731E         1
Snapdragon 730              1
Snapdragon 855              1
Snapdragon 8+ Gen 2         1
Helio  G37                  1
Snapdragon  210             1
Snapdragon 615              1
Helio MT6580                1
Unisoc                      1
Tiger  T610                 1
Snapdragon  6 Gen 1         1
Dimensity  9200             1
Kirin  9000                 1
Snapdragon 732G             1
Fusion APL1024              1
Unisoc T610                 1
Unisoc T117                 1
Snapdragon 720G             1
Unisoc  SC9832E             1
Tiger T606                  1
Sanpdragon 680              1
Snapdragon 835              1
Snapdragon  680             1
Snapdragon 888+             1
Exynos 7904                 1
Dimensity 8100 Ultra        1
Snapdragon  782G            1
Exynos  9611                1
Kirin 9000E                 1
Snapdragon 662              1
Unisoc SC7731E              1
Spreadtrum  SC7731          1
Helio A25                   1
Snapdragon  730G            1
Snapdragon  712             1
Snapdragon 8 Gen1           1
Helio  P22                  1
Dimensity 1100 5G           1
Snapdragon  765G            1
Snapdragon 730G             1
Snapdragon  865             1
Kirin 990                   1
Exynos 2100                 1
Snapdragon  662             1
Google Tensor 3             1
Helio   G90T                1
Snapdragon 675              1
Snapdragon 680              1
Snapdragon  778G+           1
Qualcomm Snapdragon 670     1
Samsung Exynos 7885         1
Kirin 659                   1
Qualcomm Snapdragon 625     1
Snapdragon  7 Gen2          1
(28 nm)                     1
Kirin  810                  1
Helio  P65                  1
Spreadtrum  SC9832E         1
Snapdragon  690             1
Helio  G88                  1
Dimensity 1000+             1
Helio  G90T                 1
Helio P23                   1
Snapdragon 665              1
Snapdragon  855             1
Snapdragon 870              1
Snapdragon MSM8939          1
Unisoc  A55                 1
Snapdragon 450              1
Snapdragon 710              1
Exynos 7885                 1
Spreadtrum  SC9832E         1
Google  Tensor 3            1
Name: count, dtype: int64

In [80]:
df["processor_name"]=df["processor_name"].str.strip()

In [81]:
df[df["processor_name"].str.contains("Core")][["processor_name",	"num_cores","processor_speed"]].shift(1,axis=1)

     processor_name            num_cores     processor_speed
118            None  Octa Core Processor                 NaN
143            None            Quad Core   1.4 GHz Processor
188            None            Quad Core   1.6 GHz Processor
201            None            Octa Core     2 GHz Processor
309            None            Octa Core     2 GHz Processor
315            None            Quad Core   1.3 GHz Processor
496            None  Octa Core Processor                 NaN
529            None  Octa Core Processor                 NaN
587            None            Octa Core     2 GHz Processor
758            None            Quad Core   1.6 GHz Processor
778            None            Octa Core   2.2 GHz Processor
794            None            Quad Core   1.3 GHz Processor
825            None  Octa Core Processor                 NaN
826            None  Octa Core Processor                 NaN
875            None  Octa Core Processor                 NaN
948            None  Octa Core Processor                 NaN
949            None  Octa Core Processor                 NaN
991            None            Octa Core   1.8 GHz Processor
1005           None            Quad Core   1.3 GHz Processor
1019           None  Octa Core Processor                 NaN

In [82]:
temp_df=df[df["processor_name"].str.contains("Core")][["processor_name","num_cores","processor_speed"]].shift(1,axis=1)

In [83]:
df.loc[temp_df.index,["processor_name","num_cores","processor_speed"]]=temp_df

In [84]:
df["processor_name"].value_counts()

processor_name
Helio P35                  30
Dimensity 700 5G           29
Snapdragon 695             29
Snapdragon 8+ Gen1         26
Snapdragon  695            24
Snapdragon 680             24
Snapdragon 8 Gen2          23
Helio G35                  20
Snapdragon  680            19
Snapdragon  8 Gen1         18
Snapdragon 8 Gen1          18
Snapdragon 870             16
Bionic A15                 16
Helio G96                  15
Dimensity  810 5G          15
Helio G99                  14
Helio G80                  14
Snapdragon  8+ Gen1        13
Dimensity 1080             12
Dimensity 810 5G           12
Snapdragon  888            12
Snapdragon 778G            12
Dimensity  920 5G          11
Helio G37                  11
Snapdragon 888             11
Bionic  A16                10
Helio A22                  10
Helio G95                  10
Helio G25                  10
Helio  G85                 10
Snapdragon  778G            9
Tiger T612                  9
Snapdragon 720G             9
Snapdragon 865              9
Bionic A14                  8
Helio G85                   8
Helio G88                   8
Dimensity 1300              8
Dimensity 700               7
Snapdragon  870             7
Dimensity 800U              6
Helio P22                   6
Helio  G96                  6
Dimensity 8100 Max          6
Dimensity 9000 Plus         6
Snapdragon  7 Gen1          6
Unisoc  T606                6
Snapdragon 765G             6
Exynos 850                  6
A13 Bionic                  5
Dimensity 8200              5
Dimensity 1200              5
Exynos  2100                5
Snapdragon 778G Plus        5
Dimensity  8100             5
Dimensity 900               5
Unisoc  SC9863A             5
Snapdragon  732G            5
Exynos 990                  4
Snapdragon  480             4
Google  Tensor              4
Snapdragon  865             4
Exynos 1330                 4
Dimensity 720               4
Dimensity 9000              4
Exynos  1280                4
Snapdragon 888+             4
Snapdragon 4 Gen 1          4
Snapdragon  750G            4
Snapdragon 778G+            4
Exynos 1280                 4
Snapdragon 732G             3
Exynos  850                 3
Dimensity  1300             3
Dimensity  900              3
Dimensity 8100-Max          3
Snapdragon  8 Gen2          3
Tiger  T616                 3
Dimensity 9200              3
Snapdragon 480+             3
Dimensity  930              3
Snapdragon 460              3
Dimensity 810               3
Dimensity  700 5G           3
Snapdragon 7 Gen1           3
Helio  G25                  3
Helio  G99                  3
Snapdragon  765G            3
Tiger T610                  3
Snapdragon 845              3
Exynos  990                 3
Snapdragon 662              3
Snapdragon  720G            3
Snapdragon  888+            3
Qualcomm 215                3
Helio P60                   3
Snapdragon  665             3
Exynos 9825                 3
Snapdragon 439              3
Unisoc T612                 2
Snapdragon  4 Gen 1         2
Snapdragon 6 Gen 1          2
Helio G70                   2
Snapdragon 678              2
Bionic  A15                 2
Snapdragon 855+             2
Snapdragon  778G Plus       2
Snapdragon  675             2
Snapdragon 690              2
Helio  P22                  2
Dimensity  8200             2
Helio                       2
Dimensity 920 5G            2
Tiger  T310                 2
Dimensity  900 5G           2
SC9863A                     2
Unisoc SC9863A              2
Exynos 9820                 2
Dimensity  9000             2
Snapdragon 425              2
Snapdragon  439             2
Helio P70                   2
Spreadtrum  SC9832E         2
Snapdragon 712              2
Dimensity 8100              2
Helio P95                   2
Exynos 9611                 2
Exynos 9810                 2
Unisoc  T610                2
Unisoc  SC9863a             2
Snapdragon  480+            2
Bionic A16                  2
Kirin  990                  2
Tiger T616                  2
Exynos 1200                 1
Google  Tensor G2           1
Exynos 1380                 1
Tiger T310                  1
Tiger T7150                 1
Tiger T700                  1
Snapdragon 730              1
Snapdragon 8+ Gen 2         1
Snapdragon 855              1
Google Tensor G2            1
Exynos  2300                1
Apple  A13                  1
Helio  G37                  1
Unisoc  SC9836A             1
Dimensity  1200 Max         1
Dimensity 930               1
Google Tensor               1
Snapdragon 835              1
Unisoc  SC9832E             1
Snapdragon  210             1
Sanpdragon 680              1
Helio  G95                  1
Helio MT6580                1
Snapdragon 615              1
Tiger T606                  1
Unisoc T606                 1
Snapdragon  810             1
Bionic  A17                 1
Spreadtrum  SC7731E         1
Unisoc                      1
Snapdragon 801              1
Snapdragon 860              1
Helio  P35                  1
Snapdragon 775              1
Dimensity 1100 5G           1
Snapdragon  6 Gen 1         1
Snapdragon 730G             1
Dimensity  9200             1
Exynos 7904                 1
Snapdragon  782G            1
Exynos  9611                1
Dimensity 8100 Ultra        1
Kirin 9000E                 1
Spreadtrum  SC7731          1
Tiger  T610                 1
Kirin  9000                 1
Unisoc T117                 1
Fusion APL1024              1
Unisoc T610                 1
Google Tensor 3             1
Snapdragon  730G            1
Snapdragon  712             1
Unisoc SC7731E              1
Helio A25                   1
Snapdragon 675              1
Kirin 990                   1
Exynos 2100                 1
Helio   G90T                1
(28 nm)                     1
Kirin  810                  1
Helio  P65                  1
Qualcomm Snapdragon 670     1
Samsung Exynos 7885         1
Snapdragon  778G+           1
Snapdragon  662             1
Qualcomm Snapdragon 625     1
Kirin 659                   1
Helio  G88                  1
Snapdragon  7 Gen2          1
Dimensity 1000+             1
Snapdragon 665              1
Snapdragon  855             1
Snapdragon  690             1
Helio  G90T                 1
Helio P23                   1
Unisoc  A55                 1
Snapdragon MSM8939          1
Snapdragon 450              1
Snapdragon 710              1
Exynos 7885                 1
Google  Tensor 3            1
Name: count, dtype: int64

In [85]:
df[df["processor_name"]=="(28 nm)"]

,index,brand_name,model,price,rating,sim,has_dual_sim,has_5g,has_nfc,has_ir_blaster,processor_name,num_cores,processor_speed,processor,ram,battery,display,camera,card,os
856,858,Samsung,Samsung Galaxy A01 Core,4999,NaN,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi",True,False,False,False,(28 nm),Quad Core,1.5 GHz Processor,"(28 nm), Quad Core, 1.5 GHz Processor","1 GB RAM, 16 GB inbuilt",3000 mAh Battery,"5.3 inches, 720 x 1480 px Display",8 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v10

In [86]:
df.loc[856,"processor_name"]="Mediatek MT6739 (28 nm)"

In [87]:
processor_brand=df["processor_name"].str.split(" ").str.get(0)

In [88]:
df.insert(11,"processor_brand",processor_brand)

In [89]:
df["num_cores"].value_counts()

num_cores
 Octa Core              866
 Hexa Core               31
 Quad Core               31
 Octa Core Processor     19
Octa Core Processor       9
 Hexa Core Processor      8
Quad Core                 6
Octa Core                 5
Name: count, dtype: int64

In [90]:
df["num_cores"]=df["num_cores"].str.strip()

In [91]:
df["num_cores"].value_counts()

num_cores
Octa Core              871
Quad Core               37
Hexa Core               31
Octa Core Processor     28
Hexa Core Processor      8
Name: count, dtype: int64

In [92]:
df["num_cores"]=df["num_cores"].str.replace("Octa Core Processor","Octa Core").str.replace("Hexa Core Processor","Hexa Core")

In [93]:
df["num_cores"].value_counts()

num_cores
Octa Core    899
Hexa Core     39
Quad Core     37
Name: count, dtype: int64

In [94]:
df["processor_speed"].value_counts()

processor_speed
2 GHz Processor       146
2.2 GHz Processor     135
2.4 GHz Processor     128
3.2 GHz Processor      94
2.3 GHz Processor      86
3 GHz Processor        53
2.84 GHz Processor     36
2.05 GHz Processor     28
1.8 GHz Processor      23
2.5 GHz Processor      23
1.6 GHz Processor      20
2.85 GHz Processor     19
3.22 GHz Processor     18
3.1 GHz Processor      15
2.6 GHz Processor      14
2.9 GHz Processor      13
1.3 GHz Processor      10
1.82 GHz Processor     10
2.73 GHz Processor      9
2.8 GHz Processor       9
2.36 GHz Processor      8
3.05 GHz Processor      8
1.4 GHz Processor       5
2.65 GHz Processor      5
2.7 GHz Processor       5
1.5 GHz Processor       4
2.96 GHz Processor      3
2.86 GHz Processor      3
3.13 GHz Processor      2
1.1 GHz Processor       1
2.37 GHz Processor      1
2.35 GHz Processor      1
1.99 GHz Processor      1
1.95 GHz Processor      1
2.1 GHz Processor       1
1.2 GHz Processor       1
Name: count, dtype: int64

In [95]:
df["processor_speed"]=df["processor_speed"].str.strip().str.split(" ").str.get(0)

In [96]:
df["processor_speed"].value_counts()

processor_speed
2 GHz       146
2.2 GHz     135
2.4 GHz     128
3.2 GHz      94
2.3 GHz      86
3 GHz        53
2.84 GHz     36
2.05 GHz     28
1.8 GHz      23
2.5 GHz      23
1.6 GHz      20
2.85 GHz     19
3.22 GHz     18
3.1 GHz      15
2.6 GHz      14
2.9 GHz      13
1.3 GHz      10
1.82 GHz     10
2.73 GHz      9
2.8 GHz       9
2.36 GHz      8
3.05 GHz      8
1.4 GHz       5
2.65 GHz      5
2.7 GHz       5
1.5 GHz       4
2.96 GHz      3
2.86 GHz      3
3.13 GHz      2
1.1 GHz       1
2.37 GHz      1
2.35 GHz      1
1.99 GHz      1
1.95 GHz      1
2.1 GHz       1
1.2 GHz       1
Name: count, dtype: int64

In [97]:
ram_capacity=df["ram"].str.strip().str.split(",").str.get(0).str.strip().str.split(" ").str.get(0)

In [98]:
df.insert(16,"ram_capacity",ram_capacity)

In [99]:
internal_memory=df["ram"].str.strip().str.split(",").str.get(1).str.strip().str.split(" ").str.get(0)

In [100]:
df.insert(17,"internal_memory",internal_memory)

In [101]:
df["ram_capacity"].value_counts()

ram_capacity
8 GB      339
6 GB      234
4 GB      215
12 GB      85
3 GB       54
2 GB       32
16 GB       9
1 GB        7
18 GB       2
64 GB       2
512 GB      1
512 MB      1
64 MB       1
Name: count, dtype: int64

In [102]:
df[(df["ram_capacity"]=="64 GB") | (df["ram_capacity"]=="512 GB") | (df["ram_capacity"]=="512 MB") | (df["ram_capacity"]=="64 MB")]

,index,brand_name,model,price,rating,sim,has_dual_sim,has_5g,has_nfc,has_ir_blaster,...,processor_speed,processor,ram,ram_capacity,internal_memory,battery,display,camera,card,os
439,441,Apple,Apple iPhone SE 3 2022,43900,NaN,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,True,False,...,3.22 GHz,"Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,64 GB,NaN,None,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v15
483,485,Huawei,Huawei Mate 50 RS Porsche Design,239999,81.0,"Dual Sim, 3G, 4G, VoLTE, Wi-Fi, NFC, IR Blaster",True,False,True,True,...,3.2 GHz,"Snapdragon 8+ Gen1, Octa Core, 3.2 GHz Processor",512 GB inbuilt,512 GB,NaN,4700 mAh Battery with 66W Fast Charging,"6.74 inches, 1212 x 2616 px, 120 Hz Display",50 MP + 48 MP + 13 MP Triple Rear & 13 MP Fron...,"Memory Card (Hybrid), upto 256 GB",Hongmeng OS v3.0
486,488,Nokia,Nokia 8000 4G,6899,NaN,"Dual Sim, 3G, 4G, Wi-Fi",True,False,False,False,...,1.1 GHz,"Snapdragon 210, Quad Core, 1.1 GHz Processor","512 MB RAM, 4 GB inbuilt",512 MB,4 GB,1500 mAh Battery,"2.8 inches, 240 x 320 px Display",2 MP Rear Camera,Memory Card Supported,NaN
627,629,Nokia,Nokia 225 4G,3589,NaN,"Dual Sim, 3G, 4G, VoLTE",True,False,False,False,...,NaN,Unisoc T117,"64 MB RAM, 128 MB inbuilt",64 MB,128 MB,1150 mAh Battery,"2.4 inches, 240 x 320 px Display",0.3 MP Rear Camera,"Memory Card Supported, upto 32 GB",RTOS (Series 30+)
762,764,Apple,Apple iPhone SE 4,49990,60.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,True,False,...,3.22 GHz,"Bionic A15, Hexa Core, 3.22 GHz Processor",64 GB inbuilt,64 GB,NaN,None,"6.1 inches, 750 x 1580 px Display",12 MP Rear & 10.8 MP Front Camera,Memory Card Not Supported,iOS v16

In [103]:
df.loc[[439,762],["ram_capacity","internal_memory"]]=[["4 GB","64 GB"],["4 GB","64 GB"]]

In [104]:
df.loc[[483],["ram_capacity","internal_memory"]]=["12 GB","512 GB"]

In [105]:
df.drop([486,627],inplace=True)

In [106]:
df["ram_capacity"].value_counts()

ram_capacity
8 GB     339
6 GB     234
4 GB     217
12 GB     86
3 GB      54
2 GB      32
16 GB      9
1 GB       7
18 GB      2
Name: count, dtype: int64

In [107]:
df["internal_memory"].value_counts()

internal_memory
128 GB    523
64 GB     193
256 GB    157
32 GB      67
512 GB     22
16 GB      12
1 TB        5
8 GB        1
Name: count, dtype: int64

In [108]:
df["battery"].value_counts()

battery
5000 mAh Battery with 33W Fast Charging      103
5000 mAh Battery with 18W Fast Charging       89
5000 mAh Battery                              74
5000 mAh Battery with 67W Fast Charging       30
5000 mAh Battery with 10W Fast Charging       28
5000 mAh Battery with 15W Fast Charging       24
5000 mAh Battery with 25W Fast Charging       23
5000 mAh Battery with 120W Fast Charging      21
5000 mAh Battery with 80W Fast Charging       19
6000 mAh Battery with 18W Fast Charging       19
5000 mAh Battery with Fast Charging           18
5000 mAh Battery with 30W Fast Charging       15
4500 mAh Battery with 33W Fast Charging       14
6000 mAh Battery with 15W Fast Charging       13
4500 mAh Battery with 80W Fast Charging       12
4500 mAh Battery with 25W Fast Charging       12
4500 mAh Battery with 65W Fast Charging       12
4000 mAh Battery                              12
4500 mAh Battery with 67W Fast Charging       11
4700 mAh Battery with 80W Fast Charging        9
5000 mAh Battery with 44W Fast Charging        8
4700 mAh Battery with 66W Fast Charging        7
4230 mAh Battery                               7
5000 mAh Battery with 20W Fast Charging        6
5000 mAh Battery with 65W Fast Charging        6
5000 mAh Battery with 45W Fast Charging        6
4300 mAh Battery with 30W Fast Charging        6
6000 mAh Battery with 65W Fast Charging        6
4000 mAh Battery with 33W Fast Charging        6
4600 mAh Battery with 66W Fast Charging        5
4500 mAh Battery with Fast Charging            5
5020 mAh Battery with 18W Fast Charging        5
4700 mAh Battery with 120W Fast Charging       5
5080 mAh Battery with 67W Fast Charging        5
4800 mAh Battery with 150W Fast Charging       5
5000 mAh Battery with 100W Fast Charging       4
4500 mAh Battery with 45W Fast Charging        4
5500 mAh Battery with 67W Fast Charging        4
5020 mAh Battery with 33W Fast Charging        4
4800 mAh Battery with 66W Fast Charging        4
4500 mAh Battery with 66W Fast Charging        4
4323 mAh Battery with Fast Charging            4
6000 mAh Battery with 25W Fast Charging        4
3000 mAh Battery                               4
6000 mAh Battery with 33W Fast Charging        4
4500 mAh Battery with 120W Fast Charging       4
6000 mAh Battery                               4
4000 mAh Battery with Fast Charging            4
4300 mAh Battery with 44W Fast Charging        4
4250 mAh Battery with 33W Fast Charging        3
4400 mAh Battery with 66W Fast Charging        3
4352 mAh Battery with Fast Charging            3
7000 mAh Battery with 33W Fast Charging        3
3700 mAh Battery with 25W Fast Charging        3
3095 mAh Battery with Fast Charging            3
3500 mAh Battery                               3
3200 mAh Battery with Fast Charging            3
4800 mAh Battery with 67W Fast Charging        3
4500 mAh Battery with 60W Fast Charging        3
4050 mAh Battery with 44W Fast Charging        3
3279 mAh Battery with Fast Charging            3
3240 mAh Battery with Fast Charging            3
4500 mAh Battery with 44W Fast Charging        3
4980 mAh Battery with 120W Fast Charging       3
5000 mAh Battery with 66W Fast Charging        3
4400 mAh Battery with 25W Fast Charging        3
4600 mAh Battery with 120W Fast Charging       3
4325 mAh Battery with Fast Charging            3
4030 mAh Battery                               3
4000 mAh Battery with 25W Fast Charging        3
4300 mAh Battery with 65W Fast Charging        3
4300 mAh Battery with 66W Fast Charging        3
4000 mAh Battery with 66W Fast Charging        3
6000 mAh Battery with 44W Fast Charging        3
4520 mAh Battery with 33W Fast Charging        3
5000 mAh Battery with 22.5W Fast Charging      3
4000 mAh Battery with 15W Fast Charging        3
4200 mAh Battery with 65W Fast Charging        2
4000 mAh Battery with 21W Fast Charging        2
4000 mAh Battery with 18W Fast Charging        2
3300 mAh Battery                               2
3020 mAh Battery                               2
4300 mAh Battery with 25W Fast Charging        2
4500 mAh Battery with 30W Fast Charging        2
5160 mAh Battery with 45W Fast Charging        2
3500 mAh Battery with Fast Charging            2
4610 mAh Battery with 125W Fast Charging       2
4400 mAh Battery with 68W Fast Charging        2
5160 mAh Battery with 67W Fast Charging        2
6000 mAh Battery with 20W Fast Charging        2
4350 mAh Battery with 120W Fast Charging       2
4830 mAh Battery with 66W Fast Charging        2
5003 mAh Battery with 30W Fast Charging        2
4200 mAh Battery with 33W Fast Charging        2
4200 mAh Battery with 44W Fast Charging        2
4500 mAh Battery with 100W Fast Charging       2
3110 mAh Battery                               2
4700 mAh Battery with 67W Fast Charging        2
4020 mAh Battery with 33W Fast Charging        2
4410 mAh Battery with Fast Charging            2
4200 mAh Battery with 40W Fast Charging        2
4500 mAh Battery with 150W Fast Charging       2
4200 mAh Battery with 55W Fast Charging        2
6000 mAh Battery with Fast Charging            2
4000 mAh Battery with 10W Fast Charging        2
4500 mAh Battery with 18W Fast Charging        2
3360 mAh Battery                               2
5050 mAh Battery with 18W Fast Charging        2
4450 mAh Battery with 125W Fast Charging       2
2150 mAh Battery                               1
4600 mAh Battery with 125W Fast Charging       1
4200 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 40W Fast Charging        1
6000 mAh Battery with 80W Fast Charging        1
4300 mAh Battery with 120W Fast Charging       1
2050 mAh Battery with Fast Charging            1
3900 mAh Battery with 25W Fast Charging        1
4820 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 68W Fast Charging        1
2800 mAh Battery                               1
4352 mAh Battery with 25W Fast Charging        1
4520 mAh Battery with 67W Fast Charging        1
4310 mAh Battery with 50W Fast Charging        1
5200 mAh Battery with 33W Fast Charging        1
4810 mAh Battery with 120W Fast Charging       1
4800 mAh Battery with 100W Fast Charging       1
5200 mAh Battery with 210W Fast Charging       1
4700 mAh Battery with 45W Fast Charging        1
4500 mAh Battery with 180W Fast Charging       1
4700 mAh Battery with 200W Fast Charging       1
4355 mAh Battery with 30W Fast Charging        1
5200 mAh Battery with 67W Fast Charging        1
4614 mAh Battery with 30W Fast Charging        1
4450 mAh Battery                               1
3300 mAh Battery with 15W Fast Charging        1
2438 mAh Battery with Fast Charging            1
3060 mAh Battery with Fast Charging            1
6000 mAh Battery with 120W Fast Charging       1
2275 mAh Battery                               1
4870 mAh Battery with 120W Fast Charging       1
4050 mAh Battery with 40W Fast Charging        1
5160 mAh Battery with 33W Fast Charging        1
5000 mAh Battery with 19W Fast Charging        1
4700 mAh Battery with 33W Fast Charging        1
4860 mAh Battery with 67W Fast Charging        1
6000 mAh Battery with 45W Fast Charging        1
4730 mAh Battery with 80W Fast Charging        1
1900 mAh Battery                               1
5600 mAh Battery with 68W Fast Charging        1
5050 mAh Battery with 10W Fast Charging        1
4080 mAh Battery with 18W Fast Charging        1
4300 mAh Battery with 210W Fast Charging       1
5000 mAh Battery with 60W Fast Charging        1
3520 mAh Battery with Fast Charging            1
5000 mAh Battery with 135W Fast Charging       1
5000 mAh Battery with 165W Fast Charging       1
4300 mAh Battery with 33W Fast Charging        1
5100 mAh Battery with 45W Fast Charging        1
4100 mAh Battery with 15W Fast Charging        1
2800 mAh Battery with Fast Charging            1
4200 mAh Battery with 66W Fast Charging        1
4700 mAh Battery with Fast Charging            1
21000 mAh Battery with 33W Fast Charging       1
4600 mAh Battery with 240W Fast Charging       1
1821 mAh Battery with 18W Fast Charging        1
4500 mAh Battery with 50W Fast Charging        1
9800 mAh Battery with 66W Fast Charging        1
2230 mAh Battery                               1
3500 mAh Battery with 18W Fast Charging        1
4470 mAh Battery with 18W Fast Charging        1
4800 mAh Battery with 125W Fast Charging       1
4500 mAh Battery with 20W Fast Charging        1
4000 mAh Battery with 45W Fast Charging        1
4015 mAh Battery with 30W Fast Charging        1
4300 mAh Battery with 45W Fast Charging        1
4020 mAh Battery with 68W Fast Charging        1
3285 mAh Battery with Fast Charging            1
4300 mAh Battery with 67W Fast Charging        1
5100 mAh Battery with 120W Fast Charging       1
4300 mAh Battery with Fast Charging            1
4000 mAh Battery with 20W Fast Charging        1
4000 mAh Battery with 30W Fast Charging        1
4000 mAh Battery with 22.5W Fast Charging      1
4830 mAh Battery with 67W Fast Charging        1
5020 mAh Battery with 67W Fast Charging        1
4800 mAh Battery with 25W Fast Charging        1
3700 mAh Battery with Fast Charging            1
4200 mAh Battery with 67W Fast Charging        1
3315 mAh Battery                               1
5080 mAh Battery with 120W Fast Charging       1
5100 mAh Battery with 18W Fast Charging        1
5050 mAh Battery                               1
4800 mAh Battery                               1
4360 mAh Battery with 66W Fast Charging        1
4310 mAh Battery with 30W Fast Charging        1
4800 mAh Battery with 33W Fast Charging        1
3600 mAh Battery with 18W Fast Charging        1
7000 mAh Battery with Fast Charging            1
2000 mAh Battery                               1
3100 mAh Battery with 15W Fast Charging        1
4100 mAh Battery                               1
22000 mAh Battery with 33W Fast Charging       1
7000 mAh Battery                               1
5020 mAh Battery with 22.5W Fast Charging      1
5000 mAh Battery with 40W Fast Charging        1
7000 mAh Battery with 18W Fast Charging        1
2400 mAh Battery                               1
4350 mAh Battery with 65W Fast Charging        1
4000 mAh Battery with 27W Fast Charging        1
3200 mAh Battery                               1
2500 mAh Battery                               1
3700 mAh Battery with 18W Fast Charging        1
4532 mAh Battery with Fast Charging            1
3000 mAh Battery with 10W Fast Charging        1
5050 mAh Battery with 30W Fast Charging        1
5065 mAh Battery with 67W Fast Charging        1
4620 mAh Battery with 18W Fast Charging        1
4100 mAh Battery with 33W Fast Charging        1
4780 mAh Battery with 30W Fast Charging        1
3730 mAh Battery with Fast Charging            1
4500 mAh Battery with 55W Fast Charging        1
3400 mAh Battery with Fast Charging            1
2730 mAh Battery                               1
5180 mAh Battery with 10W Fast Charging        1
4500 mAh Battery with 68W Fast Charging        1
8000 mAh Battery                               1
5000 mAh Battery with 68W Fast Charging        1
5000 mAh Battery with 68.2W Fast Charging      1
Name: count, dtype: int64

In [109]:
battery_capacity=df["battery"].str.strip().str.split("with").str.get(0).str.split(" ").str.get(0)

In [110]:
df.insert(16,"battery_capacity",battery_capacity)

In [111]:
has_fast_charging=df["battery"].str.strip().str.contains("Fast Charging")

In [112]:
df.insert(17,"has_fast_charging",has_fast_charging)

In [113]:
fast_charging=df["battery"].str.strip().str.split("with").str.get(1).str.strip().str.split(" ").str.get(0)

In [114]:
df.insert(18,"fast_charging",fast_charging)

In [115]:
def fast_charging_extractor(item):
  if type(item) == str:
    if item == "Fast":
      return 0
    else:
      return item
  else:
    return item

In [116]:
df["fast_charging"].apply(fast_charging_extractor)

0        100W
1         33W
2         15W
3           0
4         67W
5         25W
6           0
7        120W
8         33W
9         80W
10        33W
11        33W
12        67W
13        18W
14        45W
15          0
16        10W
17        80W
18        80W
19        18W
20       100W
21        66W
22        67W
23        33W
24       100W
25          0
26        33W
27          0
28        44W
29       100W
30        33W
31        67W
32        67W
33        NaN
34        25W
35        25W
36        66W
37        45W
38       210W
39        67W
40        67W
41        67W
42        30W
43        67W
44        44W
45        25W
46        33W
47        NaN
48        10W
49        33W
50        15W
51       120W
52        18W
53        30W
54        33W
55        18W
56          0
57        33W
58        45W
59        33W
60        67W
61        66W
62        25W
63        18W
64        33W
65        66W
66        80W
67       120W
68        25W
69        67W
70        NaN
71        44W
72        18W
73       150W
74        18W
75        NaN
76          0
77        67W
78        33W
79        NaN
80        33W
81        15W
82        18W
83        18W
84        15W
85        33W
86        25W
87        33W
88        33W
89        25W
90        18W
91          0
92          0
93        80W
94        NaN
95        33W
96          0
97       120W
98        66W
99        18W
100         0
101       33W
102       68W
103       33W
104       50W
105      120W
106      120W
107       25W
108       44W
109       80W
110       45W
111      None
112       67W
113       25W
114       10W
115       80W
116       25W
117       66W
118      120W
119       25W
120       68W
121       80W
122         0
123       33W
124       25W
125       44W
126       20W
127       33W
128       25W
129         0
130       18W
131       18W
132       NaN
133       33W
134       67W
135       67W
136       NaN
137       18W
138       33W
139       80W
140       18W
141       67W
142       33W
143       NaN
144       18W
145       15W
146       66W
147       25W
148       18W
149      None
150       33W
151       33W
152       25W
153       67W
154       33W
156       NaN
157       33W
158       65W
159       67W
160       33W
161       33W
162         0
163       80W
164      120W
165       15W
166       33W
167       33W
168       66W
169       18W
170       NaN
171       67W
172       33W
173       18W
174         0
175       18W
176       33W
177       33W
178       18W
179       44W
180       33W
181      180W
182       10W
183      125W
184       25W
185       33W
186      120W
187       30W
188       NaN
189       10W
190       NaN
191       NaN
192       25W
193       65W
194       68W
195       18W
196       80W
197       33W
198       67W
199       15W
200       33W
201       25W
202      125W
203      120W
204       33W
205       18W
206       33W
207       25W
208       18W
209       67W
210         0
211       66W
212       18W
213       33W
214       NaN
215       40W
216       30W
217       33W
218       44W
219       NaN
220       67W
221       60W
222       18W
223       33W
224       33W
225       10W
226       NaN
227       33W
228       80W
229       80W
230       80W
231      200W
232       18W
233       18W
234       33W
235       44W
236       67W
237       10W
238       33W
239       44W
240      120W
241       33W
242       67W
243       66W
244       30W
245       33W
246       33W
247         0
248       30W
249       80W
250       20W
251       45W
252       45W
253       18W
254       67W
255       67W
256       33W
257       45W
258       18W
259       30W
260       18W
261       18W
262       NaN
263         0
264       25W
265       33W
266       65W
267      100W
268       67W
269       66W
270       15W
272       30W
273       33W
274       18W
275       67W
276      120W
277         0
278       33W
279       NaN
280       65W
281       44W
282         0
283       18W
284      120W
285       25W
286       67W
287       67W
288       33W
289       18W
290         0
291       15W
292       33W
293       33W
294       NaN
295       25W
296      125W
297       33W
298       67W
299       NaN
300       10W
301       67W
302       NaN
303       NaN
304       18W
305       33W
306       15W
307      None
308      150W
309       25W
310       65W
311         0
312       25W
313       45W
314       33W
315       NaN
316       66W
317       15W
318       80W
319       66W
320      120W
321       25W
322       NaN
323         0
324       25W
325       NaN
326       30W
327       33W
328       25W
329       18W
330       18W
331       33W
332       66W
333       25W
334       30W
335       67W
336       33W
337       NaN
338       20W
339       65W
340       33W
341       NaN
342       33W
343         0
344       33W
345       33W
346         0
347      120W
348      120W
349       10W
350       20W
351       10W
352       NaN
353       NaN
354      120W
355       10W
356       18W
357       33W
358       NaN
359       67W
360       33W
361      120W
362      120W
363      None
364       45W
365       44W
366      150W
367       NaN
368       25W
369       33W
370       30W
371       33W
372       33W
373       25W
374         0
375       15W
377       66W
378       33W
379       65W
380       25W
381       25W
382       10W
383       NaN
384       NaN
385       18W
386       66W
387       60W
388       15W
389       33W
390       18W
391       33W
392       44W
393       15W
394       33W
395       33W
396       18W
397       15W
398       33W
399       NaN
401      240W
402         0
403       10W
404       67W
405       33W
406       33W
407       80W
408       65W
409       67W
410      120W
411       33W
412       30W
413       15W
414       18W
415       33W
416       65W
417       65W
418       NaN
419       67W
420         0
421       33W
422      125W
423       67W
424       66W
425       80W
426       44W
427       18W
428      120W
429       33W
430       33W
431       NaN
432       15W
433       33W
434       67W
435         0
436       NaN
437       10W
438       33W
439      None
440       25W
441       33W
442       NaN
443       15W
444       10W
445       65W
446      120W
447       NaN
448      None
449       18W
450       18W
451       80W
452       19W
453       33W
454       15W
455       NaN
456       30W
457         0
458       66W
459       33W
460       18W
461       NaN
462       40W
463      120W
464       80W
465       15W
466       10W
467       18W
468       80W
469       33W
470       33W
471       NaN
472       45W
474       15W
475       25W
476         0
477       NaN
478       NaN
479       10W
480       NaN
481       NaN
482       80W
483       66W
484       33W
485       44W
487       21W
488         0
489       30W
490       45W
491       66W
492       18W
493      135W
494       18W
495       80W
496         0
497       67W
498       33W
499       80W
500       66W
501       18W
502       NaN
503       20W
504       25W
505       NaN
506         0
507       10W
508       66W
509       33W
510       NaN
511       15W
512       15W
513       60W
514       18W
515       18W
516      150W
517      210W
518       15W
519       80W
520         0
521       44W
522       33W
523       60W
524       NaN
525       33W
526       65W
527         0
528       33W
529       25W
530       33W
531       18W
534       80W
535       30W
536       10W
537       18W
538       18W
539       18W
540       65W
541      120W
542       33W
543       66W
544       25W
545       68W
546       18W
547       18W
548       33W
549       33W
550       44W
552       33W
553       33W
554       66W
555       30W
556       25W
557       67W
558       18W
559       80W
560       65W
561       67W
562       NaN
563       33W
564       18W
565       65W
566       65W
567       15W
568      165W
569       25W
570         0
571       33W
572       25W
574       NaN
576       NaN
577       NaN
578       66W
579      120W
580       20W
581       33W
583      125W
584       67W
585       66W
586       18W
587       25W
588       NaN
589       18W
590       18W
591       80W
592      120W
593       80W
594      120W
595       NaN
596       NaN
597       NaN
598       18W
599       18W
600       18W
601       15W
602       33W
603       65W
604       30W
605       45W
606       18W
607       NaN
609       33W
610       NaN
612       33W
613       66W
614       80W
615       67W
616       67W
617       33W
618       44W
619       33W
620       30W
621       18W
622       18W
623       18W
624       NaN
625       NaN
626       33W
628      None
629       21W
630       18W
631       25W
632       15W
633       67W
634       80W
635       10W
636         0
637      120W
638       33W
639       33W
641       45W
642      120W
643      120W
644       NaN
646       25W
648       18W
649       66W
650       NaN
651       65W
652       50W
653       18W
654       NaN
655       NaN
656       18W
658       10W
659      120W
660       44W
661       33W
662       44W
663       18W
664       33W
666       18W
667       33W
668       18W
669      120W
670       18W
671       NaN
672       18W
673       15W
674       18W
675       67W
676       33W
677       33W
678       33W
679       33W
680       25W
681       18W
682         0
683       25W
684         0
686      120W
687       15W
688       15W
689       10W
690       18W
691       18W
692      120W
693       33W
694       15W
695      120W
696       NaN
697       NaN
698       30W
700       80W
701       18W
702       67W
703       33W
704         0
705       18W
706       33W
707       15W
708       30W
709       45W
710       30W
711       NaN
712       18W
713       30W
714       20W
715       15W
716       45W
717       NaN
718       18W
719       80W
720       33W
721       65W
722       68W
723      120W
724       66W
725       NaN
726       66W
727       67W
728         0
729       33W
730       NaN
731       NaN
732      120W
733       18W
734       66W
735       NaN
736       66W
737       67W
738       NaN
739       30W
740       65W
741       20W
742       65W
743       18W
744       NaN
745       33W
746       33W
747       33W
749       25W
750       18W
751       30W
752       20W
753       NaN
755         0
756       10W
758       NaN
759       67W
760      120W
761      100W
762      None
763       18W
764         0
765       67W
766       44W
767       33W
768       67W
769       80W
770       65W
771       NaN
772     22.5W
773       15W
774       45W
775       18W
776       67W
777       80W
778       NaN
779       18W
780       NaN
781         0
782       NaN
783       44W
784       NaN
785       67W
786       NaN
787       15W
788         0
789       18W
790       67W
791       18W
792         0
793       NaN
794       NaN
795       18W
796       25W
797       33W
798       25W
799       30W
800       40W
801       NaN
802         0
803       NaN
804       NaN
805         0
806      120W
807       15W
808         0
809         0
810      120W
811       18W
812       80W
813         0
814         0
815       18W
816       18W
818       NaN
819       33W
820       18W
821       10W
822      120W
823       33W
824       33W
825         0
826         0
827       80W
828         0
829       33W
830       NaN
831       67W
832       18W
833       67W
834       18W
836       18W
837       18W
838       NaN
839       18W
840         0
841       NaN
842       65W
843       67W
844       NaN
845       33W
847       18W
848       33W
849      120W
850         0
851       18W
853      None
854       10W
855       30W
856       NaN
858       65W
859       NaN
860       18W
861       NaN
862       40W
863       18W
864       18W
865     22.5W
866       18W
867       10W
868       18W
869       15W
870       25W
871       NaN
872       NaN
874       33W
875     22.5W
876       45W
877       80W
878       18W
879       33W
880       NaN
883       NaN
884       66W
885       40W
886         0
887      120W
888       80W
889       18W
890      150W
891      120W
892       33W
893       33W
894       NaN
895       18W
896       44W
897       NaN
898       65W
899       30W
900       NaN
901       18W
902       67W
903       20W
904       65W
905       30W
906       30W
907       NaN
908       25W
909       65W
910       65W
911       15W
912       18W
913      None
914      None
915       NaN
916       18W
918       NaN
919       65W
920       25W
921       27W
922       18W
923       NaN
924       NaN
926       NaN
928         0
929       18W
931       NaN
933       33W
934       80W
935       10W
936       10W
937       NaN
938       NaN
939       55W
940       10W
941       67W
942       10W
943       25W
944       33W
945      125W
946      150W
947      100W
948         0
949       18W
950       33W
951      150W
952       18W
953       44W
954       66W
955       80W
956       NaN
957       55W
958       33W
959      120W
960       15W
961         0
962       30W
963       NaN
964       33W
965       NaN
966       18W
967       67W
968       66W
969         0
970       18W
971       66W
972       NaN
973       15W
974       65W
975       18W
976       15W
977       15W
978       NaN
979       NaN
980       33W
981       18W
982       18W
983       NaN
984       NaN
985       30W
986       NaN
987       30W
989         0
990         0
991       15W
992       NaN
993       55W
994         0
995       NaN
996       NaN
997       NaN
998       10W
999     22.5W
1001      10W
1002      33W
1003      NaN
1004      68W
1005      NaN
1006      NaN
1007      67W
1008      68W
1009      80W
1010      10W
1011     120W
1012      NaN
1013      67W
1014      66W
1015    68.2W
1016    22.5W
1017      67W
1018        0
1019        0
Name: fast_charging, dtype: object

In [117]:
df["fast_charging"]=df["fast_charging"].apply(fast_charging_extractor)

In [118]:
screen_size=df["display"].str.strip().str.split(",").str.get(0)

In [119]:
df.insert(22,"screen_size",screen_size)

In [120]:
resolution=df["display"].str.strip().str.split(",").str.get(1).str.strip().str.split("Display").str.get(0)

In [121]:
df.insert(23,"resolution",resolution)

In [122]:
refresh_rate=df["display"].str.strip().str.split(",").str.get(2).str.strip().str.split("Display").str.get(0).apply(lambda x: "60 Hz" if pd.isna(x) else x)

In [123]:
df.insert(24,"refresh_rate",refresh_rate)

In [124]:
df.screen_size.value_counts()

screen_size
6.5 inches     119
6.67 inches     97
6.7 inches      93
6.6 inches      91
6.43 inches     43
6.4 inches      43
6.58 inches     40
6.8 inches      35
6.78 inches     33
6.1 inches      31
6.44 inches     31
6.51 inches     29
6.52 inches     27
6.56 inches     25
6.55 inches     25
6.53 inches     25
6.73 inches     18
6.62 inches     18
6 inches        11
6.59 inches     10
6.71 inches      9
6.2 inches       9
6.82 inches      7
4.7 inches       5
5 inches         5
6.9 inches       5
6.3 inches       5
6.22 inches      4
8.03 inches      4
5.4 inches       4
6.35 inches      4
6.57 inches      3
7.1 inches       3
6.95 inches      3
6.76 inches      3
5.5 inches       3
6.28 inches      3
7.6 inches       3
6.47 inches      3
6.72 inches      2
5.9 inches       2
6.49 inches      2
7.8 inches       2
6.83 inches      2
5.45 inches      2
6.81 inches      2
6.18 inches      2
6.39 inches      2
6.74 inches      2
6.06 inches      2
5.7 inches       1
6.14 inches      1
6.68 inches      1
6.54 inches      1
3.54 inches      1
6.26 inches      1
8.02 inches      1
5.42 inches      1
6.36 inches      1
6.64 inches      1
6.66 inches      1
4.5 inches       1
7.92 inches      1
6.91 inches      1
6.92 inches      1
7.4 inches       1
6.38 inches      1
8.01 inches      1
7 inches         1
4 inches         1
5.3 inches       1
5.84 inches      1
7.2 inches       1
6.34 inches      1
6.09 inches      1
8 inches         1
5.2 inches       1
6.75 inches      1
5.86 inches      1
Name: count, dtype: int64

In [125]:
df["resolution"].value_counts()

resolution
1080 x 2400 px     274
720 x 1600 px      116
1080 x 2400 px      68
1080 x 2412 px      58
1080 x 2408 px      45
720 x 1600 px       33
1080 x 2460 px      30
1440 x 3200 px      27
1080 x 2340 px      26
1080 x 2408 px      20
1080 x 2340 px      17
720 x 1560 px       13
1170 x 2532 px      12
1440 x 3216 px      10
720 x 1612 px       10
1080 x 2460 px       9
1600 x 720 px        8
720 x 1612 px        8
1080 x 2448 px       7
720 x 1520 px        7
2400 x 1080 px       6
1080 x 2376 px       6
720 x 1440 px        5
1080 x 2520 px       5
1080 x 2404 px       5
720 x 1544 px        5
1290 x 2796 px       5
1284 x 2778 px       5
1080 x 2280 px       4
750 x 1334 px        4
1170 x 2532 px       4
1916 x 2160 px       4
1440 x 3080 px       4
1520 x 720 px        4
1080 x 1920 px       4
1440 x 3040 px       4
1080 x 2388 px       4
1440 x 3200 px       4
1440 x 3120 px       4
720 x 1650 px        3
1116 x 2480 px       3
2400 x 1080 px       3
1179 x 2556 px       3
2408 x 1080 px       3
1284 x 2778 px       3
828 x 1792 px        3
1792 x 1920 px       3
1600 x 720 px        3
1220 x 2712 px       3
2460 x 1080 px       3
854 x 480 px         3
720 x 1280 px        2
1440 x 1920 px       2
1080 x 2160 px       2
1344 x 2772 px       2
1260 x 2800 px       2
1080 x 2246 px       2
1080 x 2640 px       2
720 x 1640 px        2
1812 x 2176 px       2
1644 x 3840 px       2
1612 x 720 px        2
1440 x 3088 px       1
640 x 960 px         1
1400 x 3200 px       1
1612 x 720 px        1
1914 x 2160 px       1
1080 x 2388 px       1
480 x 854 px         1
1640 x 720 px        1
720 x 1680 px        1
2088 x 2250 px       1
1200 x 2860 px       1
1200 x 2400 px       1
1440 x 3214 px       1
1080 x 2160 px       1
1768 x 2208 px       1
1440 x 3412 px       1
1440 x 2880 px       1
1644 x 3840 px       1
1242 x 2688 px       1
2200 x 2480 px       1
1288 x 2700 px       1
1212 x 2616 px       1
1200 x 2652 px       1
750 x 1580 px        1
1200 x 2640 px       1
1860 x 2480 px       1
1440 x 2960 px       1
1260 x 2730 px       1
1080 x 2480 px       1
1080 x 2316 px       1
480 x 640 px         1
720 x 1480 px        1
1080 x 2520 px       1
1440 x 3168 px       1
1176 x 2400 px       1
1560 x 720 px        1
2200 x 2480 px       1
2220 x 1080 px       1
Name: count, dtype: int64

In [126]:
df["refresh_rate"].value_counts()

refresh_rate
60 Hz      368
120 Hz     344
90 Hz      219
144 Hz      39
165 Hz       9
240 Hz       1
Name: count, dtype: int64

In [127]:
def camera_extractor(text):
  if "Quad" in text:
    return 4
  elif "Triple" in text:
    return 3
  elif "Dual" in text:
    return 2
  elif "0" in text:
    return 0
  else:
    return 1

In [128]:
num_rear_cameras=df["camera"].str.strip().str.split("&").str.get(0).apply(camera_extractor)

In [129]:
df.insert(26,"num_rear_cameras",num_rear_cameras)

In [130]:
num_front_cameras=df["camera"].str.strip().str.split("&").str.get(1).fillna("0").apply(camera_extractor)

In [131]:
df.insert(27,"num_front_cameras",num_front_cameras)

In [132]:
pd.set_option('display.max_columns',None)

In [133]:
primary_camera_rear=df['camera'].str.split(' ').str.get(0)

In [134]:
primary_camera_front=df['camera'].str.split('&').str.get(1).str.strip().str.split(' ').str.get(0)

In [135]:
df.insert(27,"primary_camera_rear",primary_camera_rear)
df.insert(29,"primary_camera_front",primary_camera_front)

In [136]:
df.head(2)

,index,brand_name,model,price,rating,sim,has_dual_sim,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,processor_speed,processor,ram,battery_capacity,has_fast_charging,fast_charging,ram_capacity,internal_memory,battery,screen_size,resolution,refresh_rate,display,num_rear_cameras,primary_camera_rear,num_front_cameras,primary_camera_front,camera,card,os
0,2,OnePlus,OnePlus 11 5G,54999,89.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi, NFC",True,True,True,False,Snapdragon 8 Gen2,Snapdragon,Octa Core,3.2 GHz,"Snapdragon 8 Gen2, Octa Core, 3.2 GHz Processor","12 GB RAM, 256 GB inbuilt",5000 mAh,True,100W,12 GB,256 GB,5000 mAh Battery with 100W Fast Charging,6.7 inches,1440 x 3216 px,120 Hz,"6.7 inches, 1440 x 3216 px, 120 Hz Display wit...",3,50 MP,1,16 MP,50 MP + 48 MP + 32 MP Triple Rear & 16 MP Fron...,Memory Card Not Supported,Android v13
1,3,OnePlus,OnePlus Nord CE 2 Lite 5G,19989,81.0,"Dual Sim, 3G, 4G, 5G, VoLTE, Wi-Fi",True,True,False,False,Snapdragon 695,Snapdragon,Octa Core,2.2 GHz,"Snapdragon 695, Octa Core, 2.2 GHz Processor","6 GB RAM, 128 GB inbuilt",5000 mAh,True,33W,6 GB,128 GB,5000 mAh Battery with 33W Fast Charging,6.59 inches,1080 x 2412 px,120 Hz,"6.59 inches, 1080 x 2412 px, 120 Hz Display wi...",3,64 MP,1,16 MP,64 MP + 2 MP + 2 MP Triple Rear & 16 MP Front ...,"Memory Card (Hybrid), upto 1 TB",Android v12

In [137]:
df["card"].value_counts()

card
Memory Card Not Supported              354
Memory Card Supported, upto 1 TB       171
Memory Card Supported, upto 512 GB     105
Memory Card (Hybrid), upto 1 TB         91
Memory Card Supported, upto 256 GB      89
Memory Card Supported                   88
Memory Card (Hybrid)                    31
Memory Card (Hybrid), upto 256 GB       15
Memory Card (Hybrid), upto 512 GB       11
Memory Card Supported, upto 128 GB       7
Memory Card Supported, upto 2 TB         5
Memory Card (Hybrid), upto 128 GB        3
Memory Card Supported, upto 32 GB        3
Memory Card (Hybrid), upto 64 GB         3
Memory Card (Hybrid), upto 2 TB          3
Memory Card Supported, upto 1000 GB      1
Name: count, dtype: int64

In [138]:
def has_card(text):
  if "Not" in text:
    return "No"
  elif "Hybrid" in text:
    return "Yes (Hybrid)"
  else:
    return "Yes"

In [139]:
has_memory_card=df["card"].apply(has_card)

In [140]:
df.insert(31,"has_memory_card",has_memory_card)

In [141]:
def extended_memory (text):
  if "Not" in text:
    return np.nan
  elif "upto" in text:
    x=text.split("upto")
    return x[-1]
  else:
    return "Not Specified"

In [142]:
extended_memory=df["card"].apply(extended_memory)

In [143]:
df.insert(32,"extended_memory",extended_memory)

In [144]:
df["os"]=df["os"].str.strip().str.split(" ").str.get(0)

In [145]:
df.drop(columns=['index','sim','processor','ram','battery','display','camera','card'],inplace=True)

In [146]:
df.sample(5)

,brand_name,model,price,rating,has_dual_sim,has_5g,has_nfc,has_ir_blaster,processor_name,processor_brand,num_cores,processor_speed,battery_capacity,has_fast_charging,fast_charging,ram_capacity,internal_memory,screen_size,resolution,refresh_rate,num_rear_cameras,primary_camera_rear,num_front_cameras,primary_camera_front,has_memory_card,extended_memory,os
436,OPPO,OPPO A16e,8999,65.0,True,False,False,False,Helio P22,Helio,Octa Core,2 GHz,4230 mAh,False,NaN,3 GB,32 GB,6.52 inches,720 x 1600 px,60 Hz,1,13 MP,1,5 MP,Yes (Hybrid),1 TB,Android
812,Realme,Realme GT Neo 3T (8GB RAM + 256GB),28499,82.0,True,True,False,False,Snapdragon 870,Snapdragon,Octa Core,3.2 GHz,5000 mAh,True,80W,8 GB,256 GB,6.62 inches,1080 x 2400 px,120 Hz,3,64 MP,1,16 MP,No,NaN,Android
467,Infinix,Infinix Hot 12 Play,8910,66.0,True,False,False,False,Tiger T610,Tiger,Octa Core,1.82 GHz,6000 mAh,True,18W,4 GB,64 GB,6.82 inches,1640 x 720 px,90 Hz,2,13 MP,1,8 MP,Yes,256 GB,Android
786,Micromax,Micromax IN 2C,5999,60.0,True,False,False,False,Tiger T610,Tiger,Octa Core,1.8 GHz,5000 mAh,False,NaN,3 GB,32 GB,6.52 inches,720 x 1600 px,60 Hz,1,8 MP,1,5 MP,Yes,256 GB,Android
960,Samsung,Samsung Galaxy F42 5G (8GB RAM + 128GB),22999,82.0,True,True,False,False,Dimensity 700 5G,Dimensity,Octa Core,2.2 GHz,5000 mAh,True,15W,8 GB,128 GB,6.6 inches,1080 x 2408 px,90 Hz,3,64 MP,1,8 MP,Yes,1 TB,Android

In [147]:
df.to_csv('smartphone_cleaned',index=False)